// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hetu/checkpointing/v1/checkpoint.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	github_com_hetu_project_hetu_v1_crypto_bls12381 "github.com/hetu-project/hetu/v1/crypto/bls12381"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CheckpointStatus is the status of a checkpoint.
type CheckpointStatus int32

const (
	// ACCUMULATING defines a checkpoint that is awaiting for BLS signatures.
	Accumulating CheckpointStatus = 0
	// SEALED defines a checkpoint that has accumulated sufficient BLS signatures.
	Sealed CheckpointStatus = 1
	// SUBMITTED defines a checkpoint that is included on L1.
	Submitted CheckpointStatus = 2
	// CONFIRMED defines a checkpoint that is k-deep on L1.
	Confirmed CheckpointStatus = 3
	// FINALIZED defines a checkpoint that is w-deep on L1.
	Finalized CheckpointStatus = 4
)

var CheckpointStatus_name = map[int32]string{
	0: "CKPT_STATUS_ACCUMULATING",
	1: "CKPT_STATUS_SEALED",
	2: "CKPT_STATUS_SUBMITTED",
	3: "CKPT_STATUS_CONFIRMED",
	4: "CKPT_STATUS_FINALIZED",
}

var CheckpointStatus_value = map[string]int32{
	"CKPT_STATUS_ACCUMULATING": 0,
	"CKPT_STATUS_SEALED":       1,
	"CKPT_STATUS_SUBMITTED":    2,
	"CKPT_STATUS_CONFIRMED":    3,
	"CKPT_STATUS_FINALIZED":    4,
}

func (x CheckpointStatus) String() string {
	return proto.EnumName(CheckpointStatus_name, int32(x))
}

func (CheckpointStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_24bb387b8ff9a72c, []int{0}
}

// RawCheckpoint wraps the BLS multi sig with metadata
type RawCheckpoint struct {
	// epoch_num defines the epoch number the raw checkpoint is for
	EpochNum uint64 `protobuf:"varint,1,opt,name=epoch_num,json=epochNum,proto3" json:"epoch_num,omitempty"`
	// block_hash defines the 'BlockID.Hash', which is the hash of
	// the latest block
	BlockHash *BlockHash `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3,customtype=BlockHash" json:"block_hash,omitempty"`
	// bitmap defines the bitmap that indicates the signers of the BLS multi sig
	Bitmap []byte `protobuf:"bytes,3,opt,name=bitmap,proto3" json:"bitmap,omitempty"`
	// bls_multi_sig defines the multi sig that is aggregated from individual BLS
	// sigs
	BlsMultiSig *github_com_hetu_project_hetu_v1_crypto_bls12381.Signature `protobuf:"bytes,4,opt,name=bls_multi_sig,json=blsMultiSig,proto3,customtype=github.com/hetu-project/hetu/v1/crypto/bls12381.Signature" json:"bls_multi_sig,omitempty"`
}

func (m *RawCheckpoint) Reset()         { *m = RawCheckpoint{} }
func (m *RawCheckpoint) String() string { return proto.CompactTextString(m) }
func (*RawCheckpoint) ProtoMessage()    {}
func (*RawCheckpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_24bb387b8ff9a72c, []int{0}
}
func (m *RawCheckpoint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RawCheckpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RawCheckpoint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RawCheckpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawCheckpoint.Merge(m, src)
}
func (m *RawCheckpoint) XXX_Size() int {
	return m.Size()
}
func (m *RawCheckpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_RawCheckpoint.DiscardUnknown(m)
}

var xxx_messageInfo_RawCheckpoint proto.InternalMessageInfo

func (m *RawCheckpoint) GetEpochNum() uint64 {
	if m != nil {
		return m.EpochNum
	}
	return 0
}

func (m *RawCheckpoint) GetBitmap() []byte {
	if m != nil {
		return m.Bitmap
	}
	return nil
}

// RawCheckpointWithMeta wraps the raw checkpoint with metadata.
type RawCheckpointWithMeta struct {
	Ckpt *RawCheckpoint `protobuf:"bytes,1,opt,name=ckpt,proto3" json:"ckpt,omitempty"`
	// status defines the status of the checkpoint
	Status CheckpointStatus `protobuf:"varint,2,opt,name=status,proto3,enum=hetu.checkpointing.v1.CheckpointStatus" json:"status,omitempty"`
	// bls_aggr_pk defines the aggregated BLS public key
	BlsAggrPk *github_com_hetu_project_hetu_v1_crypto_bls12381.PublicKey `protobuf:"bytes,3,opt,name=bls_aggr_pk,json=blsAggrPk,proto3,customtype=github.com/hetu-project/hetu/v1/crypto/bls12381.PublicKey" json:"bls_aggr_pk,omitempty"`
	// power_sum defines the accumulated voting power for the checkpoint
	PowerSum uint64 `protobuf:"varint,4,opt,name=power_sum,json=powerSum,proto3" json:"power_sum,omitempty"`
	// lifecycle defines the lifecycle of this checkpoint, i.e., each state
	// transition and the time (in both timestamp and block height) of this
	// transition.
	Lifecycle []*CheckpointStateUpdate `protobuf:"bytes,5,rep,name=lifecycle,proto3" json:"lifecycle,omitempty"`
}

func (m *RawCheckpointWithMeta) Reset()         { *m = RawCheckpointWithMeta{} }
func (m *RawCheckpointWithMeta) String() string { return proto.CompactTextString(m) }
func (*RawCheckpointWithMeta) ProtoMessage()    {}
func (*RawCheckpointWithMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_24bb387b8ff9a72c, []int{1}
}
func (m *RawCheckpointWithMeta) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RawCheckpointWithMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RawCheckpointWithMeta.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RawCheckpointWithMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawCheckpointWithMeta.Merge(m, src)
}
func (m *RawCheckpointWithMeta) XXX_Size() int {
	return m.Size()
}
func (m *RawCheckpointWithMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_RawCheckpointWithMeta.DiscardUnknown(m)
}

var xxx_messageInfo_RawCheckpointWithMeta proto.InternalMessageInfo

func (m *RawCheckpointWithMeta) GetCkpt() *RawCheckpoint {
	if m != nil {
		return m.Ckpt
	}
	return nil
}

func (m *RawCheckpointWithMeta) GetStatus() CheckpointStatus {
	if m != nil {
		return m.Status
	}
	return Accumulating
}

func (m *RawCheckpointWithMeta) GetPowerSum() uint64 {
	if m != nil {
		return m.PowerSum
	}
	return 0
}

func (m *RawCheckpointWithMeta) GetLifecycle() []*CheckpointStateUpdate {
	if m != nil {
		return m.Lifecycle
	}
	return nil
}

// CheckpointStateUpdate defines a state transition on the checkpoint.
type CheckpointStateUpdate struct {
	// state defines the event of a state transition towards this state
	State CheckpointStatus `protobuf:"varint,1,opt,name=state,proto3,enum=hetu.checkpointing.v1.CheckpointStatus" json:"state,omitempty"`
	// block_height is the height of the hetu block that triggers the state
	// update
	BlockHeight uint64 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// block_time is the timestamp in the hetu block that triggers the state
	// update
	BlockTime *time.Time `protobuf:"bytes,3,opt,name=block_time,json=blockTime,proto3,stdtime" json:"block_time,omitempty"`
}

func (m *CheckpointStateUpdate) Reset()         { *m = CheckpointStateUpdate{} }
func (m *CheckpointStateUpdate) String() string { return proto.CompactTextString(m) }
func (*CheckpointStateUpdate) ProtoMessage()    {}
func (*CheckpointStateUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_24bb387b8ff9a72c, []int{2}
}
func (m *CheckpointStateUpdate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CheckpointStateUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CheckpointStateUpdate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CheckpointStateUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckpointStateUpdate.Merge(m, src)
}
func (m *CheckpointStateUpdate) XXX_Size() int {
	return m.Size()
}
func (m *CheckpointStateUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckpointStateUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_CheckpointStateUpdate proto.InternalMessageInfo

func (m *CheckpointStateUpdate) GetState() CheckpointStatus {
	if m != nil {
		return m.State
	}
	return Accumulating
}

func (m *CheckpointStateUpdate) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *CheckpointStateUpdate) GetBlockTime() *time.Time {
	if m != nil {
		return m.BlockTime
	}
	return nil
}

// BlsSig wraps the BLS sig with metadata.
type BlsSig struct {
	// epoch_num defines the epoch number that the BLS sig is signed on
	EpochNum uint64 `protobuf:"varint,1,opt,name=epoch_num,json=epochNum,proto3" json:"epoch_num,omitempty"`
	// block_hash defines the 'BlockID.Hash', which is the hash of
	// the block that individual BLS sigs are signed on
	BlockHash *BlockHash                                                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3,customtype=BlockHash" json:"block_hash,omitempty"`
	BlsSig    *github_com_hetu_project_hetu_v1_crypto_bls12381.Signature `protobuf:"bytes,3,opt,name=bls_sig,json=blsSig,proto3,customtype=github.com/hetu-project/hetu/v1/crypto/bls12381.Signature" json:"bls_sig,omitempty"`
	// can't find cosmos_proto.scalar when compiling due to cosmos v0.45.4 does
	// not support scalar string signer_address = 4 [(cosmos_proto.scalar) =
	// "cosmos.AddressString"]
	// the signer_address defines the address of the
	// signer
	SignerAddress string `protobuf:"bytes,4,opt,name=signer_address,json=signerAddress,proto3" json:"signer_address,omitempty"`
	// validator_address defines the validator's consensus address
	ValidatorAddress string `protobuf:"bytes,5,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
}

func (m *BlsSig) Reset()         { *m = BlsSig{} }
func (m *BlsSig) String() string { return proto.CompactTextString(m) }
func (*BlsSig) ProtoMessage()    {}
func (*BlsSig) Descriptor() ([]byte, []int) {
	return fileDescriptor_24bb387b8ff9a72c, []int{3}
}
func (m *BlsSig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BlsSig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BlsSig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BlsSig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlsSig.Merge(m, src)
}
func (m *BlsSig) XXX_Size() int {
	return m.Size()
}
func (m *BlsSig) XXX_DiscardUnknown() {
	xxx_messageInfo_BlsSig.DiscardUnknown(m)
}

var xxx_messageInfo_BlsSig proto.InternalMessageInfo

func (m *BlsSig) GetEpochNum() uint64 {
	if m != nil {
		return m.EpochNum
	}
	return 0
}

func (m *BlsSig) GetSignerAddress() string {
	if m != nil {
		return m.SignerAddress
	}
	return ""
}

func (m *BlsSig) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

// ValidatorWithBLSSet defines a set of validators with their BLS public keys
type ValidatorWithBlsKeySet struct {
	ValSet []*ValidatorWithBlsKey `protobuf:"bytes,1,rep,name=val_set,json=valSet,proto3" json:"val_set,omitempty"`
}

func (m *ValidatorWithBlsKeySet) Reset()         { *m = ValidatorWithBlsKeySet{} }
func (m *ValidatorWithBlsKeySet) String() string { return proto.CompactTextString(m) }
func (*ValidatorWithBlsKeySet) ProtoMessage()    {}
func (*ValidatorWithBlsKeySet) Descriptor() ([]byte, []int) {
	return fileDescriptor_24bb387b8ff9a72c, []int{4}
}
func (m *ValidatorWithBlsKeySet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorWithBlsKeySet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorWithBlsKeySet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorWithBlsKeySet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorWithBlsKeySet.Merge(m, src)
}
func (m *ValidatorWithBlsKeySet) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorWithBlsKeySet) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorWithBlsKeySet.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorWithBlsKeySet proto.InternalMessageInfo

func (m *ValidatorWithBlsKeySet) GetValSet() []*ValidatorWithBlsKey {
	if m != nil {
		return m.ValSet
	}
	return nil
}

// ValidatorWithBlsKey couples validator address, voting power, and its bls
// public key
type ValidatorWithBlsKey struct {
	// validator_address is the address of the validator
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	// bls_pub_key is the BLS public key of the validator
	BlsPubKey []byte `protobuf:"bytes,2,opt,name=bls_pub_key,json=blsPubKey,proto3" json:"bls_pub_key,omitempty"`
	// voting_power is the voting power of the validator at the given epoch
	VotingPower uint64 `protobuf:"varint,3,opt,name=voting_power,json=votingPower,proto3" json:"voting_power,omitempty"`
	// dispatcher_url is the dispatcher URL of the validator
	DispatcherUrl string `protobuf:"bytes,4,opt,name=dispatcher_url,json=dispatcherUrl,proto3" json:"dispatcher_url,omitempty"`
}

func (m *ValidatorWithBlsKey) Reset()         { *m = ValidatorWithBlsKey{} }
func (m *ValidatorWithBlsKey) String() string { return proto.CompactTextString(m) }
func (*ValidatorWithBlsKey) ProtoMessage()    {}
func (*ValidatorWithBlsKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_24bb387b8ff9a72c, []int{5}
}
func (m *ValidatorWithBlsKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorWithBlsKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorWithBlsKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorWithBlsKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorWithBlsKey.Merge(m, src)
}
func (m *ValidatorWithBlsKey) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorWithBlsKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorWithBlsKey.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorWithBlsKey proto.InternalMessageInfo

func (m *ValidatorWithBlsKey) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *ValidatorWithBlsKey) GetBlsPubKey() []byte {
	if m != nil {
		return m.BlsPubKey
	}
	return nil
}

func (m *ValidatorWithBlsKey) GetVotingPower() uint64 {
	if m != nil {
		return m.VotingPower
	}
	return 0
}

func (m *ValidatorWithBlsKey) GetDispatcherUrl() string {
	if m != nil {
		return m.DispatcherUrl
	}
	return ""
}

// Validator is a message that denotes a validator
type Validator struct {
	// addr is the validator's address
	Addr []byte `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	// power is the validator's voting power
	Power int64 `protobuf:"varint,2,opt,name=power,proto3" json:"power,omitempty"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_24bb387b8ff9a72c, []int{6}
}
func (m *Validator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return m.Size()
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetAddr() []byte {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *Validator) GetPower() int64 {
	if m != nil {
		return m.Power
	}
	return 0
}

func init() {
	proto.RegisterEnum("hetu.checkpointing.v1.CheckpointStatus", CheckpointStatus_name, CheckpointStatus_value)
	proto.RegisterType((*RawCheckpoint)(nil), "hetu.checkpointing.v1.RawCheckpoint")
	proto.RegisterType((*RawCheckpointWithMeta)(nil), "hetu.checkpointing.v1.RawCheckpointWithMeta")
	proto.RegisterType((*CheckpointStateUpdate)(nil), "hetu.checkpointing.v1.CheckpointStateUpdate")
	proto.RegisterType((*BlsSig)(nil), "hetu.checkpointing.v1.BlsSig")
	proto.RegisterType((*ValidatorWithBlsKeySet)(nil), "hetu.checkpointing.v1.ValidatorWithBlsKeySet")
	proto.RegisterType((*ValidatorWithBlsKey)(nil), "hetu.checkpointing.v1.ValidatorWithBlsKey")
	proto.RegisterType((*Validator)(nil), "hetu.checkpointing.v1.Validator")
}

func init() {
	proto.RegisterFile("hetu/checkpointing/v1/checkpoint.proto", fileDescriptor_24bb387b8ff9a72c)
}

var fileDescriptor_24bb387b8ff9a72c = []byte{
	// 903 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcf, 0x6b, 0x1b, 0x47,
	0x18, 0xd5, 0x5a, 0x6b, 0x25, 0x1a, 0x49, 0x41, 0x9d, 0xc6, 0x41, 0xa8, 0x20, 0x29, 0xa2, 0x3f,
	0x4c, 0x9a, 0xae, 0xb0, 0x42, 0x20, 0x2d, 0x84, 0x20, 0xc9, 0x72, 0xab, 0xda, 0x72, 0xc4, 0xae,
	0x94, 0x42, 0x20, 0x2c, 0xb3, 0xab, 0xf1, 0xee, 0x54, 0xb3, 0xda, 0x65, 0x67, 0x46, 0xa9, 0x7a,
	0x2f, 0x14, 0x9f, 0xf2, 0x0f, 0x18, 0x0a, 0xbd, 0xf6, 0x8f, 0xe8, 0xb1, 0xc7, 0x1c, 0x4b, 0x0a,
	0x69, 0xb0, 0x2f, 0xa5, 0x7f, 0x45, 0x99, 0x59, 0xc9, 0x8e, 0x12, 0x85, 0xb6, 0x21, 0xb7, 0xd9,
	0x37, 0xef, 0x1b, 0xbd, 0xef, 0x7d, 0xef, 0x43, 0xe0, 0x63, 0x1f, 0x73, 0xd1, 0x70, 0x7d, 0xec,
	0x4e, 0xa2, 0x90, 0x4c, 0x39, 0x99, 0x7a, 0x8d, 0xd9, 0xce, 0x4b, 0x80, 0x11, 0xc5, 0x21, 0x0f,
	0xe1, 0x96, 0xe4, 0x19, 0x2b, 0x3c, 0x63, 0xb6, 0x53, 0xae, 0x7a, 0x61, 0xe8, 0x51, 0xdc, 0x50,
	0x24, 0x47, 0x1c, 0x35, 0x38, 0x09, 0x30, 0xe3, 0x28, 0x88, 0x92, 0xba, 0xf2, 0x55, 0x2f, 0xf4,
	0x42, 0x75, 0x6c, 0xc8, 0x53, 0x82, 0xd6, 0xff, 0xd0, 0x40, 0xc1, 0x44, 0x8f, 0x3b, 0xe7, 0xcf,
	0xc1, 0x0f, 0x40, 0x16, 0x47, 0xa1, 0xeb, 0xdb, 0x53, 0x11, 0x94, 0xb4, 0x9a, 0xb6, 0xad, 0x9b,
	0x97, 0x15, 0x70, 0x28, 0x02, 0x78, 0x13, 0x00, 0x87, 0x86, 0xee, 0xc4, 0xf6, 0x11, 0xf3, 0x4b,
	0x1b, 0x35, 0x6d, 0x3b, 0xdf, 0x2e, 0x3c, 0x7b, 0x5e, 0xcd, 0xb6, 0x25, 0xfa, 0x15, 0x62, 0xbe,
	0x99, 0x75, 0x96, 0x47, 0x78, 0x0d, 0x64, 0x1c, 0xc2, 0x03, 0x14, 0x95, 0xd2, 0x92, 0x69, 0x2e,
	0xbe, 0x20, 0x02, 0x05, 0x87, 0x32, 0x3b, 0x10, 0x94, 0x13, 0x9b, 0x11, 0xaf, 0xa4, 0xab, 0x87,
	0xee, 0x3e, 0x7b, 0x5e, 0xfd, 0xdc, 0x23, 0xdc, 0x17, 0x8e, 0xe1, 0x86, 0x41, 0x43, 0x36, 0xfa,
	0x59, 0x14, 0x87, 0xdf, 0x62, 0x97, 0xab, 0x0f, 0xe5, 0x47, 0x3c, 0x8f, 0x78, 0xd8, 0x70, 0x28,
	0xdb, 0x69, 0xde, 0xba, 0xb3, 0x63, 0x58, 0xc4, 0x9b, 0x22, 0x2e, 0x62, 0x6c, 0xe6, 0x1c, 0xca,
	0xfa, 0xf2, 0x49, 0x8b, 0x78, 0x5f, 0xe8, 0x7f, 0xfd, 0x54, 0xd5, 0xea, 0x2f, 0x36, 0xc0, 0xd6,
	0x4a, 0x77, 0xdf, 0x10, 0xee, 0xf7, 0x31, 0x47, 0xf0, 0x0e, 0xd0, 0xdd, 0x49, 0xc4, 0x55, 0x83,
	0xb9, 0xe6, 0x87, 0xc6, 0x5a, 0x53, 0x8d, 0x95, 0x5a, 0x53, 0x55, 0xc0, 0x7b, 0x20, 0xc3, 0x38,
	0xe2, 0x82, 0xa9, 0xf6, 0xaf, 0x34, 0x3f, 0x79, 0x43, 0xed, 0x45, 0xa1, 0xa5, 0xe8, 0xe6, 0xa2,
	0x0c, 0x3e, 0x02, 0x52, 0xa9, 0x8d, 0x3c, 0x2f, 0xb6, 0xa3, 0x49, 0x62, 0xcd, 0xdb, 0xf5, 0x3e,
	0x10, 0x0e, 0x25, 0xee, 0x3e, 0x9e, 0x4b, 0xd3, 0x59, 0xcb, 0xf3, 0xe2, 0xc1, 0x44, 0xce, 0x2f,
	0x0a, 0x1f, 0xe3, 0xd8, 0x66, 0x22, 0x50, 0xc6, 0xea, 0xe6, 0x65, 0x05, 0x58, 0x22, 0x80, 0x5f,
	0x83, 0x2c, 0x25, 0x47, 0xd8, 0x9d, 0xbb, 0x14, 0x97, 0x36, 0x6b, 0xe9, 0xed, 0x5c, 0xf3, 0xe6,
	0x7f, 0xd2, 0x8f, 0x47, 0xd1, 0x18, 0x71, 0x6c, 0x5e, 0x94, 0x2f, 0x2c, 0xfe, 0x55, 0x03, 0x5b,
	0x6b, 0xa9, 0xf0, 0x2e, 0xd8, 0x94, 0x1d, 0x63, 0xe5, 0xf1, 0xff, 0xf0, 0x29, 0xa9, 0x82, 0xd7,
	0x41, 0x7e, 0x11, 0x35, 0x4c, 0x3c, 0x9f, 0x2b, 0xb7, 0x75, 0x39, 0x64, 0x99, 0x2e, 0x05, 0xc1,
	0x7b, 0xcb, 0x34, 0xca, 0xac, 0x2b, 0x23, 0x73, 0xcd, 0xb2, 0x91, 0x2c, 0x82, 0xb1, 0x5c, 0x04,
	0x63, 0xb8, 0x5c, 0x84, 0xb6, 0xfe, 0xe4, 0xcf, 0xaa, 0xb6, 0x08, 0xa8, 0x44, 0x17, 0x2d, 0xfc,
	0xb0, 0x01, 0x32, 0x6d, 0xca, 0x2c, 0xe2, 0xbd, 0xcb, 0xf0, 0x3f, 0x00, 0x97, 0xe4, 0x98, 0x65,
	0xbc, 0xd3, 0xef, 0x22, 0xde, 0x19, 0x27, 0x91, 0xf8, 0x11, 0xb8, 0xc2, 0x88, 0x37, 0xc5, 0xb1,
	0x8d, 0xc6, 0xe3, 0x18, 0x33, 0xa6, 0x86, 0x9c, 0x35, 0x0b, 0x09, 0xda, 0x4a, 0x40, 0xf8, 0x29,
	0x78, 0x6f, 0x86, 0x28, 0x19, 0x23, 0x1e, 0x5e, 0x30, 0x37, 0x15, 0xb3, 0x78, 0x7e, 0xb1, 0x20,
	0x2b, 0x1f, 0x52, 0xf5, 0x47, 0xe0, 0xda, 0x83, 0xe5, 0x8d, 0x5c, 0x94, 0x36, 0x65, 0xfb, 0x78,
	0x6e, 0x61, 0x0e, 0x3b, 0xe0, 0xd2, 0x0c, 0x51, 0x9b, 0x61, 0xb9, 0x30, 0x32, 0x34, 0x37, 0xde,
	0x30, 0xcc, 0x35, 0xf5, 0x66, 0x66, 0x86, 0xa8, 0x85, 0x79, 0xfd, 0x17, 0x0d, 0xbc, 0xbf, 0xe6,
	0x7e, 0xbd, 0x52, 0x6d, 0xbd, 0x52, 0x58, 0x49, 0x96, 0x27, 0x12, 0x8e, 0x3d, 0xc1, 0xf3, 0x64,
	0x08, 0x2a, 0xfd, 0x03, 0xe1, 0xc8, 0xc7, 0xae, 0x83, 0xfc, 0x2c, 0x94, 0x6a, 0x6c, 0x95, 0x79,
	0x65, 0xbd, 0x6e, 0xe6, 0x12, 0x6c, 0x20, 0x21, 0x69, 0xe0, 0x98, 0xb0, 0x08, 0x71, 0xd7, 0xc7,
	0xb1, 0x2d, 0x62, 0xba, 0x34, 0xf0, 0x02, 0x1d, 0xc5, 0xb4, 0x7e, 0x1b, 0x64, 0xcf, 0xd5, 0x42,
	0x08, 0x74, 0xa9, 0x4c, 0xc9, 0xca, 0x9b, 0xea, 0x0c, 0xaf, 0x82, 0xcd, 0xe4, 0x37, 0xa4, 0x88,
	0xb4, 0x99, 0x7c, 0xdc, 0xf8, 0x5b, 0x03, 0xc5, 0x57, 0x23, 0x0d, 0x0d, 0x50, 0xea, 0xec, 0x0f,
	0x86, 0xb6, 0x35, 0x6c, 0x0d, 0x47, 0x96, 0xdd, 0xea, 0x74, 0x46, 0xfd, 0xd1, 0x41, 0x6b, 0xd8,
	0x3b, 0xfc, 0xb2, 0x98, 0x2a, 0x17, 0x8f, 0x4f, 0x6a, 0xf9, 0x96, 0xeb, 0x8a, 0x40, 0x50, 0x24,
	0x75, 0xc2, 0x3a, 0x80, 0x2f, 0xf3, 0xad, 0x6e, 0xeb, 0xa0, 0xbb, 0x5b, 0xd4, 0xca, 0xe0, 0xf8,
	0xa4, 0x96, 0xb1, 0x30, 0xa2, 0x78, 0x0c, 0xb7, 0xc1, 0xd6, 0x0a, 0x67, 0xd4, 0xee, 0xf7, 0x86,
	0xc3, 0xee, 0x6e, 0x71, 0xa3, 0x5c, 0x38, 0x3e, 0xa9, 0x65, 0x2d, 0xe1, 0x04, 0x84, 0xf3, 0xd7,
	0x99, 0x9d, 0xfb, 0x87, 0x7b, 0x3d, 0xb3, 0xdf, 0xdd, 0x2d, 0xa6, 0x13, 0x66, 0x27, 0x9c, 0x1e,
	0x91, 0x38, 0x78, 0x9d, 0xb9, 0xd7, 0x3b, 0x6c, 0x1d, 0xf4, 0x1e, 0x76, 0x77, 0x8b, 0x7a, 0xc2,
	0xdc, 0x23, 0x53, 0x44, 0xc9, 0xf7, 0x78, 0x5c, 0xd6, 0x7f, 0xfc, 0xb9, 0x92, 0x6a, 0xdf, 0xff,
	0xed, 0xb4, 0xa2, 0x3d, 0x3d, 0xad, 0x68, 0x2f, 0x4e, 0x2b, 0xda, 0x93, 0xb3, 0x4a, 0xea, 0xe9,
	0x59, 0x25, 0xf5, 0xfb, 0x59, 0x25, 0xf5, 0xf0, 0xf6, 0xbf, 0x05, 0xfd, 0xbb, 0x57, 0xfe, 0xea,
	0xf8, 0x3c, 0xc2, 0xcc, 0xc9, 0xa8, 0xad, 0xbd, 0xf5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xea,
	0x3d, 0x37, 0x19, 0x0d, 0x07, 0x00, 0x00,
}

func (this *RawCheckpoint) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RawCheckpoint)
	if !ok {
		that2, ok := that.(RawCheckpoint)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.EpochNum != that1.EpochNum {
		return false
	}
	if that1.BlockHash == nil {
		if this.BlockHash != nil {
			return false
		}
	} else if !this.BlockHash.Equal(*that1.BlockHash) {
		return false
	}
	if !bytes.Equal(this.Bitmap, that1.Bitmap) {
		return false
	}
	if that1.BlsMultiSig == nil {
		if this.BlsMultiSig != nil {
			return false
		}
	} else if !this.BlsMultiSig.Equal(*that1.BlsMultiSig) {
		return false
	}
	return true
}
func (this *RawCheckpointWithMeta) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RawCheckpointWithMeta)
	if !ok {
		that2, ok := that.(RawCheckpointWithMeta)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Ckpt.Equal(that1.Ckpt) {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if that1.BlsAggrPk == nil {
		if this.BlsAggrPk != nil {
			return false
		}
	} else if !this.BlsAggrPk.Equal(*that1.BlsAggrPk) {
		return false
	}
	if this.PowerSum != that1.PowerSum {
		return false
	}
	if len(this.Lifecycle) != len(that1.Lifecycle) {
		return false
	}
	for i := range this.Lifecycle {
		if !this.Lifecycle[i].Equal(that1.Lifecycle[i]) {
			return false
		}
	}
	return true
}
func (this *CheckpointStateUpdate) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CheckpointStateUpdate)
	if !ok {
		that2, ok := that.(CheckpointStateUpdate)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.State != that1.State {
		return false
	}
	if this.BlockHeight != that1.BlockHeight {
		return false
	}
	if that1.BlockTime == nil {
		if this.BlockTime != nil {
			return false
		}
	} else if !this.BlockTime.Equal(*that1.BlockTime) {
		return false
	}
	return true
}
func (m *RawCheckpoint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RawCheckpoint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RawCheckpoint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlsMultiSig != nil {
		{
			size := m.BlsMultiSig.Size()
			i -= size
			if _, err := m.BlsMultiSig.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintCheckpoint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.Bitmap) > 0 {
		i -= len(m.Bitmap)
		copy(dAtA[i:], m.Bitmap)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.Bitmap)))
		i--
		dAtA[i] = 0x1a
	}
	if m.BlockHash != nil {
		{
			size := m.BlockHash.Size()
			i -= size
			if _, err := m.BlockHash.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintCheckpoint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.EpochNum != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.EpochNum))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RawCheckpointWithMeta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RawCheckpointWithMeta) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RawCheckpointWithMeta) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Lifecycle) > 0 {
		for iNdEx := len(m.Lifecycle) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Lifecycle[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCheckpoint(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.PowerSum != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.PowerSum))
		i--
		dAtA[i] = 0x20
	}
	if m.BlsAggrPk != nil {
		{
			size := m.BlsAggrPk.Size()
			i -= size
			if _, err := m.BlsAggrPk.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintCheckpoint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Status != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x10
	}
	if m.Ckpt != nil {
		{
			size, err := m.Ckpt.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCheckpoint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CheckpointStateUpdate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CheckpointStateUpdate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CheckpointStateUpdate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockTime != nil {
		n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.BlockTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.BlockTime):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintCheckpoint(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x1a
	}
	if m.BlockHeight != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.State != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BlsSig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BlsSig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BlsSig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SignerAddress) > 0 {
		i -= len(m.SignerAddress)
		copy(dAtA[i:], m.SignerAddress)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.SignerAddress)))
		i--
		dAtA[i] = 0x22
	}
	if m.BlsSig != nil {
		{
			size := m.BlsSig.Size()
			i -= size
			if _, err := m.BlsSig.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintCheckpoint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.BlockHash != nil {
		{
			size := m.BlockHash.Size()
			i -= size
			if _, err := m.BlockHash.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintCheckpoint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.EpochNum != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.EpochNum))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ValidatorWithBlsKeySet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorWithBlsKeySet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorWithBlsKeySet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValSet) > 0 {
		for iNdEx := len(m.ValSet) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValSet[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCheckpoint(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ValidatorWithBlsKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorWithBlsKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorWithBlsKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DispatcherUrl) > 0 {
		i -= len(m.DispatcherUrl)
		copy(dAtA[i:], m.DispatcherUrl)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.DispatcherUrl)))
		i--
		dAtA[i] = 0x22
	}
	if m.VotingPower != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.VotingPower))
		i--
		dAtA[i] = 0x18
	}
	if len(m.BlsPubKey) > 0 {
		i -= len(m.BlsPubKey)
		copy(dAtA[i:], m.BlsPubKey)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.BlsPubKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Validator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Validator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Validator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Power != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.Power))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Addr) > 0 {
		i -= len(m.Addr)
		copy(dAtA[i:], m.Addr)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.Addr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCheckpoint(dAtA []byte, offset int, v uint64) int {
	offset -= sovCheckpoint(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RawCheckpoint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochNum != 0 {
		n += 1 + sovCheckpoint(uint64(m.EpochNum))
	}
	if m.BlockHash != nil {
		l = m.BlockHash.Size()
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	l = len(m.Bitmap)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	if m.BlsMultiSig != nil {
		l = m.BlsMultiSig.Size()
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	return n
}

func (m *RawCheckpointWithMeta) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Ckpt != nil {
		l = m.Ckpt.Size()
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovCheckpoint(uint64(m.Status))
	}
	if m.BlsAggrPk != nil {
		l = m.BlsAggrPk.Size()
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	if m.PowerSum != 0 {
		n += 1 + sovCheckpoint(uint64(m.PowerSum))
	}
	if len(m.Lifecycle) > 0 {
		for _, e := range m.Lifecycle {
			l = e.Size()
			n += 1 + l + sovCheckpoint(uint64(l))
		}
	}
	return n
}

func (m *CheckpointStateUpdate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.State != 0 {
		n += 1 + sovCheckpoint(uint64(m.State))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovCheckpoint(uint64(m.BlockHeight))
	}
	if m.BlockTime != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.BlockTime)
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	return n
}

func (m *BlsSig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochNum != 0 {
		n += 1 + sovCheckpoint(uint64(m.EpochNum))
	}
	if m.BlockHash != nil {
		l = m.BlockHash.Size()
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	if m.BlsSig != nil {
		l = m.BlsSig.Size()
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	l = len(m.SignerAddress)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	return n
}

func (m *ValidatorWithBlsKeySet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ValSet) > 0 {
		for _, e := range m.ValSet {
			l = e.Size()
			n += 1 + l + sovCheckpoint(uint64(l))
		}
	}
	return n
}

func (m *ValidatorWithBlsKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	l = len(m.BlsPubKey)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	if m.VotingPower != 0 {
		n += 1 + sovCheckpoint(uint64(m.VotingPower))
	}
	l = len(m.DispatcherUrl)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	return n
}

func (m *Validator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Addr)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	if m.Power != 0 {
		n += 1 + sovCheckpoint(uint64(m.Power))
	}
	return n
}

func sovCheckpoint(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCheckpoint(x uint64) (n int) {
	return sovCheckpoint(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RawCheckpoint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RawCheckpoint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RawCheckpoint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochNum", wireType)
			}
			m.EpochNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochNum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v BlockHash
			m.BlockHash = &v
			if err := m.BlockHash.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bitmap", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bitmap = append(m.Bitmap[:0], dAtA[iNdEx:postIndex]...)
			if m.Bitmap == nil {
				m.Bitmap = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlsMultiSig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_hetu_project_hetu_v1_crypto_bls12381.Signature
			m.BlsMultiSig = &v
			if err := m.BlsMultiSig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCheckpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RawCheckpointWithMeta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RawCheckpointWithMeta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RawCheckpointWithMeta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ckpt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Ckpt == nil {
				m.Ckpt = &RawCheckpoint{}
			}
			if err := m.Ckpt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= CheckpointStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlsAggrPk", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_hetu_project_hetu_v1_crypto_bls12381.PublicKey
			m.BlsAggrPk = &v
			if err := m.BlsAggrPk.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PowerSum", wireType)
			}
			m.PowerSum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PowerSum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lifecycle", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lifecycle = append(m.Lifecycle, &CheckpointStateUpdate{})
			if err := m.Lifecycle[len(m.Lifecycle)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCheckpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CheckpointStateUpdate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CheckpointStateUpdate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CheckpointStateUpdate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= CheckpointStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BlockTime == nil {
				m.BlockTime = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.BlockTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCheckpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BlsSig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BlsSig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BlsSig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochNum", wireType)
			}
			m.EpochNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochNum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v BlockHash
			m.BlockHash = &v
			if err := m.BlockHash.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlsSig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_hetu_project_hetu_v1_crypto_bls12381.Signature
			m.BlsSig = &v
			if err := m.BlsSig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCheckpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorWithBlsKeySet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorWithBlsKeySet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorWithBlsKeySet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValSet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValSet = append(m.ValSet, &ValidatorWithBlsKey{})
			if err := m.ValSet[len(m.ValSet)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCheckpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorWithBlsKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorWithBlsKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorWithBlsKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlsPubKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlsPubKey = append(m.BlsPubKey[:0], dAtA[iNdEx:postIndex]...)
			if m.BlsPubKey == nil {
				m.BlsPubKey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingPower", wireType)
			}
			m.VotingPower = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VotingPower |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DispatcherUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DispatcherUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCheckpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Validator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Validator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Validator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addr = append(m.Addr[:0], dAtA[iNdEx:postIndex]...)
			if m.Addr == nil {
				m.Addr = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Power", wireType)
			}
			m.Power = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Power |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCheckpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCheckpoint(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCheckpoint
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCheckpoint
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCheckpoint
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCheckpoint        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCheckpoint          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCheckpoint = fmt.Errorf("proto: unexpected end of group")
)
