// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hetu/checkpointing/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	github_com_hetu_project_hetu_v1_crypto_bls12381 "github.com/hetu-project/hetu/v1/crypto/bls12381"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryRawCheckpointListRequest is the request type for the
// Query/RawCheckpoints RPC method.
type QueryRawCheckpointListRequest struct {
	// status defines the status of the raw checkpoints of the query
	Status CheckpointStatus `protobuf:"varint,1,opt,name=status,proto3,enum=hetu.checkpointing.v1.CheckpointStatus" json:"status,omitempty"`
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryRawCheckpointListRequest) Reset()         { *m = QueryRawCheckpointListRequest{} }
func (m *QueryRawCheckpointListRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRawCheckpointListRequest) ProtoMessage()    {}
func (*QueryRawCheckpointListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5785623371d23004, []int{0}
}
func (m *QueryRawCheckpointListRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRawCheckpointListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRawCheckpointListRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRawCheckpointListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRawCheckpointListRequest.Merge(m, src)
}
func (m *QueryRawCheckpointListRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRawCheckpointListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRawCheckpointListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRawCheckpointListRequest proto.InternalMessageInfo

func (m *QueryRawCheckpointListRequest) GetStatus() CheckpointStatus {
	if m != nil {
		return m.Status
	}
	return Accumulating
}

func (m *QueryRawCheckpointListRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryRawCheckpointListResponse is the response type for the
// Query/RawCheckpoints RPC method.
type QueryRawCheckpointListResponse struct {
	// the order is going from the newest to oldest based on the epoch number
	RawCheckpoints []*RawCheckpointWithMetaResponse `protobuf:"bytes,1,rep,name=raw_checkpoints,json=rawCheckpoints,proto3" json:"raw_checkpoints,omitempty"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryRawCheckpointListResponse) Reset()         { *m = QueryRawCheckpointListResponse{} }
func (m *QueryRawCheckpointListResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRawCheckpointListResponse) ProtoMessage()    {}
func (*QueryRawCheckpointListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5785623371d23004, []int{1}
}
func (m *QueryRawCheckpointListResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRawCheckpointListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRawCheckpointListResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRawCheckpointListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRawCheckpointListResponse.Merge(m, src)
}
func (m *QueryRawCheckpointListResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRawCheckpointListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRawCheckpointListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRawCheckpointListResponse proto.InternalMessageInfo

func (m *QueryRawCheckpointListResponse) GetRawCheckpoints() []*RawCheckpointWithMetaResponse {
	if m != nil {
		return m.RawCheckpoints
	}
	return nil
}

func (m *QueryRawCheckpointListResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryRawCheckpointRequest is the request type for the Query/RawCheckpoint
// RPC method.
type QueryRawCheckpointRequest struct {
	// epoch_num defines the epoch for the queried checkpoint
	EpochNum uint64 `protobuf:"varint,1,opt,name=epoch_num,json=epochNum,proto3" json:"epoch_num,omitempty"`
}

func (m *QueryRawCheckpointRequest) Reset()         { *m = QueryRawCheckpointRequest{} }
func (m *QueryRawCheckpointRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRawCheckpointRequest) ProtoMessage()    {}
func (*QueryRawCheckpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5785623371d23004, []int{2}
}
func (m *QueryRawCheckpointRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRawCheckpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRawCheckpointRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRawCheckpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRawCheckpointRequest.Merge(m, src)
}
func (m *QueryRawCheckpointRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRawCheckpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRawCheckpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRawCheckpointRequest proto.InternalMessageInfo

func (m *QueryRawCheckpointRequest) GetEpochNum() uint64 {
	if m != nil {
		return m.EpochNum
	}
	return 0
}

// QueryRawCheckpointResponse is the response type for the Query/RawCheckpoint
// RPC method.
type QueryRawCheckpointResponse struct {
	RawCheckpoint *RawCheckpointWithMetaResponse `protobuf:"bytes,1,opt,name=raw_checkpoint,json=rawCheckpoint,proto3" json:"raw_checkpoint,omitempty"`
}

func (m *QueryRawCheckpointResponse) Reset()         { *m = QueryRawCheckpointResponse{} }
func (m *QueryRawCheckpointResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRawCheckpointResponse) ProtoMessage()    {}
func (*QueryRawCheckpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5785623371d23004, []int{3}
}
func (m *QueryRawCheckpointResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRawCheckpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRawCheckpointResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRawCheckpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRawCheckpointResponse.Merge(m, src)
}
func (m *QueryRawCheckpointResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRawCheckpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRawCheckpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRawCheckpointResponse proto.InternalMessageInfo

func (m *QueryRawCheckpointResponse) GetRawCheckpoint() *RawCheckpointWithMetaResponse {
	if m != nil {
		return m.RawCheckpoint
	}
	return nil
}

// QueryBlsPublicKeyListRequest is the request type for the Query/BlsPublicKeys
// RPC method.
type QueryBlsPublicKeyListRequest struct {
	// epoch_num defines the epoch for the queried bls public keys
	EpochNum uint64 `protobuf:"varint,1,opt,name=epoch_num,json=epochNum,proto3" json:"epoch_num,omitempty"`
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryBlsPublicKeyListRequest) Reset()         { *m = QueryBlsPublicKeyListRequest{} }
func (m *QueryBlsPublicKeyListRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBlsPublicKeyListRequest) ProtoMessage()    {}
func (*QueryBlsPublicKeyListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5785623371d23004, []int{4}
}
func (m *QueryBlsPublicKeyListRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBlsPublicKeyListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBlsPublicKeyListRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBlsPublicKeyListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBlsPublicKeyListRequest.Merge(m, src)
}
func (m *QueryBlsPublicKeyListRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBlsPublicKeyListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBlsPublicKeyListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBlsPublicKeyListRequest proto.InternalMessageInfo

func (m *QueryBlsPublicKeyListRequest) GetEpochNum() uint64 {
	if m != nil {
		return m.EpochNum
	}
	return 0
}

func (m *QueryBlsPublicKeyListRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// BlsPublicKeyListResponse couples validator address, voting power, and its bls
// public key
type BlsPublicKeyListResponse struct {
	// validator_address is the address of the validator
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	// bls_pub_key is the BLS public key of the validator
	BlsPubKeyHex string `protobuf:"bytes,2,opt,name=bls_pub_key_hex,json=blsPubKeyHex,proto3" json:"bls_pub_key_hex,omitempty"`
	// voting_power is the voting power of the validator at the given epoch
	VotingPower string `protobuf:"bytes,3,opt,name=voting_power,json=votingPower,proto3" json:"voting_power,omitempty"`
}

func (m *BlsPublicKeyListResponse) Reset()         { *m = BlsPublicKeyListResponse{} }
func (m *BlsPublicKeyListResponse) String() string { return proto.CompactTextString(m) }
func (*BlsPublicKeyListResponse) ProtoMessage()    {}
func (*BlsPublicKeyListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5785623371d23004, []int{5}
}
func (m *BlsPublicKeyListResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BlsPublicKeyListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BlsPublicKeyListResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BlsPublicKeyListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlsPublicKeyListResponse.Merge(m, src)
}
func (m *BlsPublicKeyListResponse) XXX_Size() int {
	return m.Size()
}
func (m *BlsPublicKeyListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlsPublicKeyListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlsPublicKeyListResponse proto.InternalMessageInfo

func (m *BlsPublicKeyListResponse) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *BlsPublicKeyListResponse) GetBlsPubKeyHex() string {
	if m != nil {
		return m.BlsPubKeyHex
	}
	return ""
}

func (m *BlsPublicKeyListResponse) GetVotingPower() string {
	if m != nil {
		return m.VotingPower
	}
	return ""
}

// QueryBlsPublicKeyListResponse is the response type for the
// Query/BlsPublicKeys RPC method.
type QueryBlsPublicKeyListResponse struct {
	ValidatorWithBlsKeys []*BlsPublicKeyListResponse `protobuf:"bytes,1,rep,name=validator_with_bls_keys,json=validatorWithBlsKeys,proto3" json:"validator_with_bls_keys,omitempty"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryBlsPublicKeyListResponse) Reset()         { *m = QueryBlsPublicKeyListResponse{} }
func (m *QueryBlsPublicKeyListResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBlsPublicKeyListResponse) ProtoMessage()    {}
func (*QueryBlsPublicKeyListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5785623371d23004, []int{6}
}
func (m *QueryBlsPublicKeyListResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBlsPublicKeyListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBlsPublicKeyListResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBlsPublicKeyListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBlsPublicKeyListResponse.Merge(m, src)
}
func (m *QueryBlsPublicKeyListResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBlsPublicKeyListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBlsPublicKeyListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBlsPublicKeyListResponse proto.InternalMessageInfo

func (m *QueryBlsPublicKeyListResponse) GetValidatorWithBlsKeys() []*BlsPublicKeyListResponse {
	if m != nil {
		return m.ValidatorWithBlsKeys
	}
	return nil
}

func (m *QueryBlsPublicKeyListResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryEpochStatusRequest is the request type for the Query/EpochStatus
// RPC method.
type QueryEpochStatusRequest struct {
	EpochNum uint64 `protobuf:"varint,1,opt,name=epoch_num,json=epochNum,proto3" json:"epoch_num,omitempty"`
}

func (m *QueryEpochStatusRequest) Reset()         { *m = QueryEpochStatusRequest{} }
func (m *QueryEpochStatusRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEpochStatusRequest) ProtoMessage()    {}
func (*QueryEpochStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5785623371d23004, []int{7}
}
func (m *QueryEpochStatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEpochStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEpochStatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEpochStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEpochStatusRequest.Merge(m, src)
}
func (m *QueryEpochStatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEpochStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEpochStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEpochStatusRequest proto.InternalMessageInfo

func (m *QueryEpochStatusRequest) GetEpochNum() uint64 {
	if m != nil {
		return m.EpochNum
	}
	return 0
}

// QueryEpochStatusResponse is the response type for the Query/EpochStatus
// RPC method.
type QueryEpochStatusResponse struct {
	Status CheckpointStatus `protobuf:"varint,1,opt,name=status,proto3,enum=hetu.checkpointing.v1.CheckpointStatus" json:"status,omitempty"`
}

func (m *QueryEpochStatusResponse) Reset()         { *m = QueryEpochStatusResponse{} }
func (m *QueryEpochStatusResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEpochStatusResponse) ProtoMessage()    {}
func (*QueryEpochStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5785623371d23004, []int{8}
}
func (m *QueryEpochStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEpochStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEpochStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEpochStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEpochStatusResponse.Merge(m, src)
}
func (m *QueryEpochStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEpochStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEpochStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEpochStatusResponse proto.InternalMessageInfo

func (m *QueryEpochStatusResponse) GetStatus() CheckpointStatus {
	if m != nil {
		return m.Status
	}
	return Accumulating
}

// RawCheckpointResponse wraps the BLS multi sig with metadata
type RawCheckpointResponse struct {
	// epoch_num defines the epoch number the raw checkpoint is for
	EpochNum uint64 `protobuf:"varint,1,opt,name=epoch_num,json=epochNum,proto3" json:"epoch_num,omitempty"`
	// block_hash_hex defines the 'BlockID.Hash', which is the hash of
	// the block that individual BLS sigs are signed on as hex string
	BlockHashHex string `protobuf:"bytes,2,opt,name=block_hash_hex,json=blockHashHex,proto3" json:"block_hash_hex,omitempty"`
	// bitmap defines the bitmap that indicates the signers of the BLS multi sig
	Bitmap []byte `protobuf:"bytes,3,opt,name=bitmap,proto3" json:"bitmap,omitempty"`
	// bls_multi_sig defines the multi sig that is aggregated from individual BLS
	// sigs
	BlsMultiSig *github_com_hetu_project_hetu_v1_crypto_bls12381.Signature `protobuf:"bytes,4,opt,name=bls_multi_sig,json=blsMultiSig,proto3,customtype=github.com/hetu-project/hetu/v1/crypto/bls12381.Signature" json:"bls_multi_sig,omitempty"`
}

func (m *RawCheckpointResponse) Reset()         { *m = RawCheckpointResponse{} }
func (m *RawCheckpointResponse) String() string { return proto.CompactTextString(m) }
func (*RawCheckpointResponse) ProtoMessage()    {}
func (*RawCheckpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5785623371d23004, []int{9}
}
func (m *RawCheckpointResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RawCheckpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RawCheckpointResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RawCheckpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawCheckpointResponse.Merge(m, src)
}
func (m *RawCheckpointResponse) XXX_Size() int {
	return m.Size()
}
func (m *RawCheckpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawCheckpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawCheckpointResponse proto.InternalMessageInfo

func (m *RawCheckpointResponse) GetEpochNum() uint64 {
	if m != nil {
		return m.EpochNum
	}
	return 0
}

func (m *RawCheckpointResponse) GetBlockHashHex() string {
	if m != nil {
		return m.BlockHashHex
	}
	return ""
}

func (m *RawCheckpointResponse) GetBitmap() []byte {
	if m != nil {
		return m.Bitmap
	}
	return nil
}

// CheckpointStateUpdateResponse defines a state transition on the checkpoint.
type CheckpointStateUpdateResponse struct {
	// state defines the event of a state transition towards this state
	State CheckpointStatus `protobuf:"varint,1,opt,name=state,proto3,enum=hetu.checkpointing.v1.CheckpointStatus" json:"state,omitempty"`
	// status_desc represents the description of status enum.
	StatusDesc string `protobuf:"bytes,2,opt,name=status_desc,json=statusDesc,proto3" json:"status_desc,omitempty"`
	// block_height is the height of the Hetu block that triggers the state
	// update
	BlockHeight uint64 `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// block_time is the timestamp in the Hetu block that triggers the state
	// update
	BlockTime *time.Time `protobuf:"bytes,4,opt,name=block_time,json=blockTime,proto3,stdtime" json:"block_time,omitempty"`
}

func (m *CheckpointStateUpdateResponse) Reset()         { *m = CheckpointStateUpdateResponse{} }
func (m *CheckpointStateUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*CheckpointStateUpdateResponse) ProtoMessage()    {}
func (*CheckpointStateUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5785623371d23004, []int{10}
}
func (m *CheckpointStateUpdateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CheckpointStateUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CheckpointStateUpdateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CheckpointStateUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckpointStateUpdateResponse.Merge(m, src)
}
func (m *CheckpointStateUpdateResponse) XXX_Size() int {
	return m.Size()
}
func (m *CheckpointStateUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckpointStateUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckpointStateUpdateResponse proto.InternalMessageInfo

func (m *CheckpointStateUpdateResponse) GetState() CheckpointStatus {
	if m != nil {
		return m.State
	}
	return Accumulating
}

func (m *CheckpointStateUpdateResponse) GetStatusDesc() string {
	if m != nil {
		return m.StatusDesc
	}
	return ""
}

func (m *CheckpointStateUpdateResponse) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *CheckpointStateUpdateResponse) GetBlockTime() *time.Time {
	if m != nil {
		return m.BlockTime
	}
	return nil
}

// RawCheckpointWithMetaResponse wraps the raw checkpoint with metadata.
type RawCheckpointWithMetaResponse struct {
	Ckpt *RawCheckpointResponse `protobuf:"bytes,1,opt,name=ckpt,proto3" json:"ckpt,omitempty"`
	// status defines the status of the checkpoint
	Status CheckpointStatus `protobuf:"varint,2,opt,name=status,proto3,enum=hetu.checkpointing.v1.CheckpointStatus" json:"status,omitempty"`
	// status_desc represents the description of status enum.
	StatusDesc string `protobuf:"bytes,3,opt,name=status_desc,json=statusDesc,proto3" json:"status_desc,omitempty"`
	// bls_aggr_pk defines the aggregated BLS public key
	BlsAggrPk *github_com_hetu_project_hetu_v1_crypto_bls12381.PublicKey `protobuf:"bytes,4,opt,name=bls_aggr_pk,json=blsAggrPk,proto3,customtype=github.com/hetu-project/hetu/v1/crypto/bls12381.PublicKey" json:"bls_aggr_pk,omitempty"`
	// power_sum defines the accumulated voting power for the checkpoint
	PowerSum string `protobuf:"bytes,5,opt,name=power_sum,json=powerSum,proto3" json:"power_sum,omitempty"`
	// lifecycle defines the lifecycle of this checkpoint, i.e., each state
	// transition and the time (in both timestamp and block height) of this
	// transition.
	Lifecycle []*CheckpointStateUpdateResponse `protobuf:"bytes,6,rep,name=lifecycle,proto3" json:"lifecycle,omitempty"`
}

func (m *RawCheckpointWithMetaResponse) Reset()         { *m = RawCheckpointWithMetaResponse{} }
func (m *RawCheckpointWithMetaResponse) String() string { return proto.CompactTextString(m) }
func (*RawCheckpointWithMetaResponse) ProtoMessage()    {}
func (*RawCheckpointWithMetaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5785623371d23004, []int{11}
}
func (m *RawCheckpointWithMetaResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RawCheckpointWithMetaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RawCheckpointWithMetaResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RawCheckpointWithMetaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawCheckpointWithMetaResponse.Merge(m, src)
}
func (m *RawCheckpointWithMetaResponse) XXX_Size() int {
	return m.Size()
}
func (m *RawCheckpointWithMetaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawCheckpointWithMetaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawCheckpointWithMetaResponse proto.InternalMessageInfo

func (m *RawCheckpointWithMetaResponse) GetCkpt() *RawCheckpointResponse {
	if m != nil {
		return m.Ckpt
	}
	return nil
}

func (m *RawCheckpointWithMetaResponse) GetStatus() CheckpointStatus {
	if m != nil {
		return m.Status
	}
	return Accumulating
}

func (m *RawCheckpointWithMetaResponse) GetStatusDesc() string {
	if m != nil {
		return m.StatusDesc
	}
	return ""
}

func (m *RawCheckpointWithMetaResponse) GetPowerSum() string {
	if m != nil {
		return m.PowerSum
	}
	return ""
}

func (m *RawCheckpointWithMetaResponse) GetLifecycle() []*CheckpointStateUpdateResponse {
	if m != nil {
		return m.Lifecycle
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryRawCheckpointListRequest)(nil), "hetu.checkpointing.v1.QueryRawCheckpointListRequest")
	proto.RegisterType((*QueryRawCheckpointListResponse)(nil), "hetu.checkpointing.v1.QueryRawCheckpointListResponse")
	proto.RegisterType((*QueryRawCheckpointRequest)(nil), "hetu.checkpointing.v1.QueryRawCheckpointRequest")
	proto.RegisterType((*QueryRawCheckpointResponse)(nil), "hetu.checkpointing.v1.QueryRawCheckpointResponse")
	proto.RegisterType((*QueryBlsPublicKeyListRequest)(nil), "hetu.checkpointing.v1.QueryBlsPublicKeyListRequest")
	proto.RegisterType((*BlsPublicKeyListResponse)(nil), "hetu.checkpointing.v1.BlsPublicKeyListResponse")
	proto.RegisterType((*QueryBlsPublicKeyListResponse)(nil), "hetu.checkpointing.v1.QueryBlsPublicKeyListResponse")
	proto.RegisterType((*QueryEpochStatusRequest)(nil), "hetu.checkpointing.v1.QueryEpochStatusRequest")
	proto.RegisterType((*QueryEpochStatusResponse)(nil), "hetu.checkpointing.v1.QueryEpochStatusResponse")
	proto.RegisterType((*RawCheckpointResponse)(nil), "hetu.checkpointing.v1.RawCheckpointResponse")
	proto.RegisterType((*CheckpointStateUpdateResponse)(nil), "hetu.checkpointing.v1.CheckpointStateUpdateResponse")
	proto.RegisterType((*RawCheckpointWithMetaResponse)(nil), "hetu.checkpointing.v1.RawCheckpointWithMetaResponse")
}

func init() { proto.RegisterFile("hetu/checkpointing/v1/query.proto", fileDescriptor_5785623371d23004) }

var fileDescriptor_5785623371d23004 = []byte{
	// 1049 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0x5b, 0x6f, 0x1b, 0x45,
	0x14, 0x80, 0xb3, 0x89, 0x13, 0xd5, 0xe3, 0x24, 0x6d, 0x47, 0x2d, 0x35, 0xa6, 0x71, 0x5a, 0x0b,
	0xda, 0x88, 0xcb, 0x4e, 0xed, 0xa4, 0x90, 0x22, 0x55, 0xa5, 0xe6, 0x56, 0x29, 0x14, 0xc2, 0x06,
	0x84, 0x44, 0x55, 0xad, 0x66, 0xd7, 0x93, 0xdd, 0xc1, 0xbb, 0x9e, 0xed, 0xce, 0xac, 0x93, 0x55,
	0xd5, 0x17, 0xf8, 0x03, 0x45, 0xfd, 0x13, 0x7d, 0xe3, 0x99, 0x7f, 0xd0, 0xc7, 0x48, 0x08, 0x09,
	0x21, 0x04, 0x28, 0xe1, 0x87, 0xa0, 0x99, 0x1d, 0xdf, 0xe2, 0x4b, 0x9d, 0xb6, 0x6f, 0xde, 0x33,
	0xe7, 0x9c, 0xf9, 0xce, 0x65, 0xce, 0x31, 0xb8, 0xec, 0x13, 0x91, 0x20, 0xd7, 0x27, 0x6e, 0x33,
	0x62, 0xb4, 0x25, 0x68, 0xcb, 0x43, 0xed, 0x2a, 0x7a, 0x90, 0x90, 0x38, 0x35, 0xa3, 0x98, 0x09,
	0x06, 0xcf, 0x4b, 0x15, 0x73, 0x40, 0xc5, 0x6c, 0x57, 0x4b, 0xe7, 0x3c, 0xe6, 0x31, 0xa5, 0x81,
	0xe4, 0xaf, 0x4c, 0xb9, 0x74, 0xd1, 0x63, 0xcc, 0x0b, 0x08, 0xc2, 0x11, 0x45, 0xb8, 0xd5, 0x62,
	0x02, 0x0b, 0xca, 0x5a, 0x5c, 0x9f, 0xae, 0xea, 0x53, 0xf5, 0xe5, 0x24, 0xbb, 0x48, 0xd0, 0x90,
	0x70, 0x81, 0xc3, 0x48, 0x2b, 0x5c, 0x19, 0x8d, 0xd3, 0x13, 0x68, 0xbd, 0xb7, 0x5d, 0xc6, 0x43,
	0xc6, 0x91, 0x83, 0x39, 0xc9, 0x60, 0x51, 0xbb, 0xea, 0x10, 0x81, 0xab, 0x28, 0xc2, 0x1e, 0x6d,
	0xa9, 0x5b, 0x33, 0xdd, 0xca, 0x53, 0x03, 0xac, 0x7c, 0x2d, 0x55, 0x2c, 0xbc, 0xf7, 0x71, 0xd7,
	0xd1, 0x17, 0x94, 0x0b, 0x8b, 0x3c, 0x48, 0x08, 0x17, 0xf0, 0x16, 0x58, 0xe0, 0x02, 0x8b, 0x84,
	0x17, 0x8d, 0x4b, 0xc6, 0xda, 0x72, 0xed, 0xaa, 0x39, 0x32, 0x64, 0xb3, 0x67, 0xbd, 0xa3, 0xd4,
	0x2d, 0x6d, 0x06, 0x3f, 0x03, 0xa0, 0x77, 0x6d, 0x71, 0xf6, 0x92, 0xb1, 0x56, 0xa8, 0x5d, 0x31,
	0x33, 0x46, 0x53, 0x32, 0x9a, 0x59, 0x42, 0x35, 0xa3, 0xb9, 0x8d, 0x3d, 0xa2, 0x2f, 0xb7, 0xfa,
	0x2c, 0x2b, 0xcf, 0x0c, 0x50, 0x1e, 0x87, 0xca, 0x23, 0xd6, 0xe2, 0x04, 0xde, 0x07, 0xa7, 0x63,
	0xbc, 0x67, 0xf7, 0xd8, 0x24, 0xf4, 0xdc, 0x5a, 0xa1, 0xb6, 0x31, 0x06, 0x7a, 0xc0, 0xd5, 0x77,
	0x54, 0xf8, 0x77, 0x89, 0xc0, 0x1d, 0x77, 0xd6, 0x72, 0xdc, 0x7f, 0xcc, 0xe1, 0xe7, 0x23, 0x22,
	0xb9, 0xfa, 0xdc, 0x48, 0xb4, 0xb3, 0xfe, 0x50, 0x36, 0xc1, 0xeb, 0xc3, 0x91, 0x74, 0x12, 0xfe,
	0x06, 0xc8, 0x93, 0x88, 0xb9, 0xbe, 0xdd, 0x4a, 0x42, 0x95, 0xf3, 0x9c, 0x75, 0x4a, 0x09, 0xbe,
	0x4c, 0xc2, 0x4a, 0x0a, 0x4a, 0xa3, 0x2c, 0x75, 0xfc, 0xf7, 0xc0, 0xf2, 0x60, 0xfc, 0xca, 0xfe,
	0x45, 0xc3, 0x5f, 0x1a, 0x08, 0xbf, 0xf2, 0x93, 0x01, 0x2e, 0xaa, 0xbb, 0xeb, 0x01, 0xdf, 0x4e,
	0x9c, 0x80, 0xba, 0x5b, 0x24, 0xed, 0xef, 0x94, 0x49, 0xe0, 0xaf, 0xac, 0x0b, 0x7e, 0x36, 0x40,
	0x71, 0x18, 0x40, 0xc7, 0xff, 0x0e, 0x38, 0xdb, 0xc6, 0x01, 0x6d, 0x60, 0xc1, 0x62, 0x1b, 0x37,
	0x1a, 0x31, 0xe1, 0x59, 0xdb, 0xe6, 0xad, 0x33, 0xdd, 0x83, 0xdb, 0x99, 0x1c, 0xbe, 0x05, 0x4e,
	0x3b, 0x01, 0xb7, 0xa3, 0xc4, 0xb1, 0x9b, 0x24, 0xb5, 0x7d, 0xb2, 0xaf, 0xb0, 0xf2, 0xd6, 0xa2,
	0xa3, 0xfc, 0x6f, 0x91, 0xf4, 0x0e, 0xd9, 0x87, 0x97, 0xc1, 0x62, 0x9b, 0xc9, 0x84, 0xd9, 0x11,
	0xdb, 0x23, 0x71, 0x71, 0x4e, 0xe9, 0x14, 0x32, 0xd9, 0xb6, 0x14, 0x55, 0x0e, 0x3a, 0x8f, 0x68,
	0x2c, 0xd8, 0x2e, 0xb8, 0xd0, 0x03, 0xdb, 0xa3, 0xc2, 0xb7, 0xe5, 0xd5, 0x4d, 0x92, 0x76, 0x1a,
	0x14, 0x8d, 0xa9, 0xd0, 0x38, 0x8f, 0xd6, 0xb9, 0xae, 0x3f, 0x59, 0xb7, 0x7a, 0xc0, 0xb7, 0x48,
	0xfa, 0x0a, 0x3b, 0xf4, 0x7d, 0x70, 0x41, 0x45, 0xf4, 0xa9, 0xac, 0x9f, 0x7e, 0xd0, 0xd3, 0xf4,
	0xe7, 0x3d, 0x50, 0x1c, 0xb6, 0xd3, 0x49, 0x78, 0xd9, 0x49, 0x52, 0xf9, 0xdd, 0x00, 0xe7, 0x47,
	0x37, 0xfe, 0xc4, 0xd6, 0x7b, 0x13, 0x2c, 0x3b, 0x01, 0x73, 0x9b, 0xb6, 0x8f, 0xb9, 0x3f, 0x58,
	0x67, 0xe6, 0x36, 0xef, 0x60, 0xee, 0xcb, 0x3a, 0xbf, 0x06, 0x16, 0x1c, 0x2a, 0x42, 0x1c, 0xa9,
	0x0a, 0x2f, 0x5a, 0xfa, 0x0b, 0x62, 0xb0, 0x24, 0x6b, 0x15, 0x26, 0x81, 0xa0, 0x36, 0xa7, 0x5e,
	0x31, 0x27, 0x8f, 0xeb, 0x37, 0xff, 0xfc, 0x7b, 0xf5, 0x86, 0x47, 0x85, 0x9f, 0x38, 0xa6, 0xcb,
	0x42, 0x24, 0x43, 0x79, 0x2f, 0x8a, 0xd9, 0x0f, 0xc4, 0x15, 0xea, 0x43, 0x8d, 0xe6, 0x38, 0x8d,
	0x04, 0x43, 0x4e, 0xc0, 0xab, 0xb5, 0xf5, 0xcd, 0xaa, 0xb9, 0x43, 0xbd, 0x16, 0x16, 0x49, 0x4c,
	0xac, 0x82, 0x13, 0xf0, 0xbb, 0xd2, 0xe5, 0x0e, 0xf5, 0x2a, 0x47, 0x06, 0x58, 0x19, 0x0c, 0x9a,
	0x7c, 0x1b, 0x35, 0xb0, 0xe8, 0x96, 0x06, 0xde, 0x04, 0xf3, 0x32, 0x07, 0xe4, 0xa4, 0x99, 0xcb,
	0xac, 0xe0, 0x2a, 0x28, 0x64, 0x29, 0xb4, 0x1b, 0x84, 0xbb, 0x3a, 0x7c, 0x90, 0x89, 0x3e, 0x21,
	0xdc, 0x95, 0x4d, 0xae, 0x53, 0x44, 0xa8, 0xe7, 0x0b, 0x95, 0x82, 0x9c, 0x84, 0x94, 0x09, 0x52,
	0x22, 0x78, 0x0b, 0x80, 0x4c, 0x45, 0xae, 0x25, 0x95, 0x84, 0x42, 0xad, 0x64, 0x66, 0x3b, 0xcb,
	0xec, 0xec, 0x2c, 0xf3, 0x9b, 0xce, 0xce, 0xaa, 0xe7, 0x1e, 0xff, 0xb3, 0x6a, 0x58, 0x79, 0x65,
	0x23, 0xa5, 0x95, 0x27, 0x73, 0x60, 0x65, 0xe2, 0xc0, 0x81, 0x1f, 0x81, 0x9c, 0xdb, 0x8c, 0x3a,
	0x43, 0xeb, 0xdd, 0x69, 0x86, 0x56, 0xb7, 0x79, 0x95, 0x65, 0x5f, 0x8b, 0xcd, 0xbe, 0xd8, 0xb2,
	0x3a, 0x96, 0xa9, 0xb9, 0xa1, 0x4c, 0xdd, 0x07, 0xb2, 0x74, 0x36, 0xf6, 0xbc, 0xd8, 0x8e, 0x9a,
	0x2f, 0xd3, 0x0c, 0xdd, 0x77, 0x2d, 0x93, 0xc4, 0x6f, 0x7b, 0x5e, 0xbc, 0xdd, 0x94, 0x8d, 0xac,
	0xc6, 0x8c, 0xcd, 0x93, 0xb0, 0x38, 0xaf, 0x6e, 0x3f, 0xa5, 0x04, 0x3b, 0x49, 0x08, 0x2d, 0x90,
	0x0f, 0xe8, 0x2e, 0x71, 0x53, 0x37, 0x20, 0xc5, 0x85, 0x89, 0x8b, 0x6d, 0x62, 0x3b, 0x59, 0x3d,
	0x37, 0xb5, 0xbf, 0xe6, 0xc1, 0xbc, 0x7a, 0xb1, 0xf0, 0x57, 0x03, 0x9c, 0x1d, 0x5a, 0xad, 0x70,
	0xdc, 0x05, 0x13, 0xff, 0x34, 0x94, 0xae, 0x9f, 0xd0, 0x2a, 0xe3, 0xaa, 0x7c, 0xf0, 0xe3, 0x6f,
	0xff, 0x3d, 0x99, 0xad, 0x42, 0x84, 0x46, 0xff, 0xd5, 0x39, 0xb6, 0xdc, 0xd1, 0xc3, 0xac, 0x30,
	0x8f, 0xe0, 0x2f, 0x06, 0x58, 0x1a, 0x70, 0x0b, 0xaf, 0x4d, 0x4d, 0xd0, 0x61, 0xae, 0x9e, 0xc0,
	0x42, 0xf3, 0xde, 0x50, 0xbc, 0xeb, 0xb0, 0x3a, 0x15, 0x2f, 0x7a, 0xd8, 0x9d, 0x51, 0x8f, 0x64,
	0xb6, 0xcf, 0x1c, 0x1f, 0xee, 0x70, 0x7d, 0x12, 0xc2, 0x98, 0xb5, 0x5b, 0xda, 0x38, 0x99, 0x91,
	0x46, 0xff, 0x50, 0xa1, 0x6f, 0xc0, 0xda, 0x18, 0x74, 0xbd, 0x1a, 0x03, 0xea, 0xaa, 0x35, 0x35,
	0xc0, 0xfe, 0xd4, 0x00, 0x85, 0xbe, 0x01, 0x0f, 0xcd, 0x49, 0x04, 0xc3, 0x1b, 0xa4, 0x84, 0xa6,
	0xd6, 0xd7, 0xb0, 0x9b, 0x0a, 0xb6, 0x06, 0xaf, 0x8d, 0x81, 0x55, 0x6c, 0x03, 0x8c, 0x28, 0xeb,
	0x8c, 0xfa, 0x57, 0xcf, 0x0e, 0xcb, 0xc6, 0xc1, 0x61, 0xd9, 0xf8, 0xf7, 0xb0, 0x6c, 0x3c, 0x3e,
	0x2a, 0xcf, 0x1c, 0x1c, 0x95, 0x67, 0xfe, 0x38, 0x2a, 0xcf, 0x7c, 0x7f, 0xfd, 0x79, 0xef, 0x75,
	0xff, 0xd8, 0x3d, 0x22, 0x8d, 0x08, 0x77, 0x16, 0xd4, 0xa8, 0x5b, 0xff, 0x3f, 0x00, 0x00, 0xff,
	0xff, 0xb9, 0x89, 0x49, 0xc3, 0x1c, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// RawCheckpointList queries all checkpoints that match the given status.
	RawCheckpointList(ctx context.Context, in *QueryRawCheckpointListRequest, opts ...grpc.CallOption) (*QueryRawCheckpointListResponse, error)
	// RawCheckpoint queries a checkpoints at a given epoch number.
	RawCheckpoint(ctx context.Context, in *QueryRawCheckpointRequest, opts ...grpc.CallOption) (*QueryRawCheckpointResponse, error)
	// BlsPublicKeyList queries a list of bls public keys of the validators at a
	// given epoch number.
	BlsPublicKeyList(ctx context.Context, in *QueryBlsPublicKeyListRequest, opts ...grpc.CallOption) (*QueryBlsPublicKeyListResponse, error)
	// EpochStatus queries the status of the checkpoint at a given epoch
	EpochStatus(ctx context.Context, in *QueryEpochStatusRequest, opts ...grpc.CallOption) (*QueryEpochStatusResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) RawCheckpointList(ctx context.Context, in *QueryRawCheckpointListRequest, opts ...grpc.CallOption) (*QueryRawCheckpointListResponse, error) {
	out := new(QueryRawCheckpointListResponse)
	err := c.cc.Invoke(ctx, "/hetu.checkpointing.v1.Query/RawCheckpointList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RawCheckpoint(ctx context.Context, in *QueryRawCheckpointRequest, opts ...grpc.CallOption) (*QueryRawCheckpointResponse, error) {
	out := new(QueryRawCheckpointResponse)
	err := c.cc.Invoke(ctx, "/hetu.checkpointing.v1.Query/RawCheckpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BlsPublicKeyList(ctx context.Context, in *QueryBlsPublicKeyListRequest, opts ...grpc.CallOption) (*QueryBlsPublicKeyListResponse, error) {
	out := new(QueryBlsPublicKeyListResponse)
	err := c.cc.Invoke(ctx, "/hetu.checkpointing.v1.Query/BlsPublicKeyList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EpochStatus(ctx context.Context, in *QueryEpochStatusRequest, opts ...grpc.CallOption) (*QueryEpochStatusResponse, error) {
	out := new(QueryEpochStatusResponse)
	err := c.cc.Invoke(ctx, "/hetu.checkpointing.v1.Query/EpochStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// RawCheckpointList queries all checkpoints that match the given status.
	RawCheckpointList(context.Context, *QueryRawCheckpointListRequest) (*QueryRawCheckpointListResponse, error)
	// RawCheckpoint queries a checkpoints at a given epoch number.
	RawCheckpoint(context.Context, *QueryRawCheckpointRequest) (*QueryRawCheckpointResponse, error)
	// BlsPublicKeyList queries a list of bls public keys of the validators at a
	// given epoch number.
	BlsPublicKeyList(context.Context, *QueryBlsPublicKeyListRequest) (*QueryBlsPublicKeyListResponse, error)
	// EpochStatus queries the status of the checkpoint at a given epoch
	EpochStatus(context.Context, *QueryEpochStatusRequest) (*QueryEpochStatusResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) RawCheckpointList(ctx context.Context, req *QueryRawCheckpointListRequest) (*QueryRawCheckpointListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawCheckpointList not implemented")
}
func (*UnimplementedQueryServer) RawCheckpoint(ctx context.Context, req *QueryRawCheckpointRequest) (*QueryRawCheckpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawCheckpoint not implemented")
}
func (*UnimplementedQueryServer) BlsPublicKeyList(ctx context.Context, req *QueryBlsPublicKeyListRequest) (*QueryBlsPublicKeyListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlsPublicKeyList not implemented")
}
func (*UnimplementedQueryServer) EpochStatus(ctx context.Context, req *QueryEpochStatusRequest) (*QueryEpochStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EpochStatus not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_RawCheckpointList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRawCheckpointListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RawCheckpointList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hetu.checkpointing.v1.Query/RawCheckpointList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RawCheckpointList(ctx, req.(*QueryRawCheckpointListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RawCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRawCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RawCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hetu.checkpointing.v1.Query/RawCheckpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RawCheckpoint(ctx, req.(*QueryRawCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BlsPublicKeyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBlsPublicKeyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BlsPublicKeyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hetu.checkpointing.v1.Query/BlsPublicKeyList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BlsPublicKeyList(ctx, req.(*QueryBlsPublicKeyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EpochStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEpochStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EpochStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hetu.checkpointing.v1.Query/EpochStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EpochStatus(ctx, req.(*QueryEpochStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hetu.checkpointing.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RawCheckpointList",
			Handler:    _Query_RawCheckpointList_Handler,
		},
		{
			MethodName: "RawCheckpoint",
			Handler:    _Query_RawCheckpoint_Handler,
		},
		{
			MethodName: "BlsPublicKeyList",
			Handler:    _Query_BlsPublicKeyList_Handler,
		},
		{
			MethodName: "EpochStatus",
			Handler:    _Query_EpochStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hetu/checkpointing/v1/query.proto",
}

func (m *QueryRawCheckpointListRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRawCheckpointListRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRawCheckpointListRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Status != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryRawCheckpointListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRawCheckpointListResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRawCheckpointListResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.RawCheckpoints) > 0 {
		for iNdEx := len(m.RawCheckpoints) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RawCheckpoints[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryRawCheckpointRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRawCheckpointRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRawCheckpointRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EpochNum != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EpochNum))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryRawCheckpointResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRawCheckpointResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRawCheckpointResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RawCheckpoint != nil {
		{
			size, err := m.RawCheckpoint.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryBlsPublicKeyListRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBlsPublicKeyListRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBlsPublicKeyListRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.EpochNum != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EpochNum))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BlsPublicKeyListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BlsPublicKeyListResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BlsPublicKeyListResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VotingPower) > 0 {
		i -= len(m.VotingPower)
		copy(dAtA[i:], m.VotingPower)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.VotingPower)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BlsPubKeyHex) > 0 {
		i -= len(m.BlsPubKeyHex)
		copy(dAtA[i:], m.BlsPubKeyHex)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.BlsPubKeyHex)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryBlsPublicKeyListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBlsPublicKeyListResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBlsPublicKeyListResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ValidatorWithBlsKeys) > 0 {
		for iNdEx := len(m.ValidatorWithBlsKeys) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorWithBlsKeys[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryEpochStatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEpochStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEpochStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EpochNum != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EpochNum))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryEpochStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEpochStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEpochStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RawCheckpointResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RawCheckpointResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RawCheckpointResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlsMultiSig != nil {
		{
			size := m.BlsMultiSig.Size()
			i -= size
			if _, err := m.BlsMultiSig.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.Bitmap) > 0 {
		i -= len(m.Bitmap)
		copy(dAtA[i:], m.Bitmap)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Bitmap)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BlockHashHex) > 0 {
		i -= len(m.BlockHashHex)
		copy(dAtA[i:], m.BlockHashHex)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.BlockHashHex)))
		i--
		dAtA[i] = 0x12
	}
	if m.EpochNum != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EpochNum))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CheckpointStateUpdateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CheckpointStateUpdateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CheckpointStateUpdateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockTime != nil {
		n6, err6 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.BlockTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.BlockTime):])
		if err6 != nil {
			return 0, err6
		}
		i -= n6
		i = encodeVarintQuery(dAtA, i, uint64(n6))
		i--
		dAtA[i] = 0x22
	}
	if m.BlockHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.StatusDesc) > 0 {
		i -= len(m.StatusDesc)
		copy(dAtA[i:], m.StatusDesc)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.StatusDesc)))
		i--
		dAtA[i] = 0x12
	}
	if m.State != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RawCheckpointWithMetaResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RawCheckpointWithMetaResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RawCheckpointWithMetaResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Lifecycle) > 0 {
		for iNdEx := len(m.Lifecycle) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Lifecycle[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.PowerSum) > 0 {
		i -= len(m.PowerSum)
		copy(dAtA[i:], m.PowerSum)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PowerSum)))
		i--
		dAtA[i] = 0x2a
	}
	if m.BlsAggrPk != nil {
		{
			size := m.BlsAggrPk.Size()
			i -= size
			if _, err := m.BlsAggrPk.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.StatusDesc) > 0 {
		i -= len(m.StatusDesc)
		copy(dAtA[i:], m.StatusDesc)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.StatusDesc)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Status != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x10
	}
	if m.Ckpt != nil {
		{
			size, err := m.Ckpt.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryRawCheckpointListRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovQuery(uint64(m.Status))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRawCheckpointListResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RawCheckpoints) > 0 {
		for _, e := range m.RawCheckpoints {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRawCheckpointRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochNum != 0 {
		n += 1 + sovQuery(uint64(m.EpochNum))
	}
	return n
}

func (m *QueryRawCheckpointResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RawCheckpoint != nil {
		l = m.RawCheckpoint.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryBlsPublicKeyListRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochNum != 0 {
		n += 1 + sovQuery(uint64(m.EpochNum))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *BlsPublicKeyListResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.BlsPubKeyHex)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.VotingPower)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryBlsPublicKeyListResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ValidatorWithBlsKeys) > 0 {
		for _, e := range m.ValidatorWithBlsKeys {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEpochStatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochNum != 0 {
		n += 1 + sovQuery(uint64(m.EpochNum))
	}
	return n
}

func (m *QueryEpochStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovQuery(uint64(m.Status))
	}
	return n
}

func (m *RawCheckpointResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochNum != 0 {
		n += 1 + sovQuery(uint64(m.EpochNum))
	}
	l = len(m.BlockHashHex)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Bitmap)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.BlsMultiSig != nil {
		l = m.BlsMultiSig.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *CheckpointStateUpdateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.State != 0 {
		n += 1 + sovQuery(uint64(m.State))
	}
	l = len(m.StatusDesc)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovQuery(uint64(m.BlockHeight))
	}
	if m.BlockTime != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.BlockTime)
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *RawCheckpointWithMetaResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Ckpt != nil {
		l = m.Ckpt.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovQuery(uint64(m.Status))
	}
	l = len(m.StatusDesc)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.BlsAggrPk != nil {
		l = m.BlsAggrPk.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.PowerSum)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.Lifecycle) > 0 {
		for _, e := range m.Lifecycle {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryRawCheckpointListRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRawCheckpointListRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRawCheckpointListRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= CheckpointStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRawCheckpointListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRawCheckpointListResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRawCheckpointListResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawCheckpoints", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RawCheckpoints = append(m.RawCheckpoints, &RawCheckpointWithMetaResponse{})
			if err := m.RawCheckpoints[len(m.RawCheckpoints)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRawCheckpointRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRawCheckpointRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRawCheckpointRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochNum", wireType)
			}
			m.EpochNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochNum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRawCheckpointResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRawCheckpointResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRawCheckpointResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawCheckpoint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RawCheckpoint == nil {
				m.RawCheckpoint = &RawCheckpointWithMetaResponse{}
			}
			if err := m.RawCheckpoint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBlsPublicKeyListRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBlsPublicKeyListRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBlsPublicKeyListRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochNum", wireType)
			}
			m.EpochNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochNum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BlsPublicKeyListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BlsPublicKeyListResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BlsPublicKeyListResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlsPubKeyHex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlsPubKeyHex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingPower", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VotingPower = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBlsPublicKeyListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBlsPublicKeyListResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBlsPublicKeyListResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorWithBlsKeys", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorWithBlsKeys = append(m.ValidatorWithBlsKeys, &BlsPublicKeyListResponse{})
			if err := m.ValidatorWithBlsKeys[len(m.ValidatorWithBlsKeys)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEpochStatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEpochStatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEpochStatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochNum", wireType)
			}
			m.EpochNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochNum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEpochStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEpochStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEpochStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= CheckpointStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RawCheckpointResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RawCheckpointResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RawCheckpointResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochNum", wireType)
			}
			m.EpochNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochNum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHashHex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockHashHex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bitmap", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bitmap = append(m.Bitmap[:0], dAtA[iNdEx:postIndex]...)
			if m.Bitmap == nil {
				m.Bitmap = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlsMultiSig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_hetu_project_hetu_v1_crypto_bls12381.Signature
			m.BlsMultiSig = &v
			if err := m.BlsMultiSig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CheckpointStateUpdateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CheckpointStateUpdateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CheckpointStateUpdateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= CheckpointStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusDesc", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StatusDesc = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BlockTime == nil {
				m.BlockTime = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.BlockTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RawCheckpointWithMetaResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RawCheckpointWithMetaResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RawCheckpointWithMetaResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ckpt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Ckpt == nil {
				m.Ckpt = &RawCheckpointResponse{}
			}
			if err := m.Ckpt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= CheckpointStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusDesc", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StatusDesc = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlsAggrPk", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_hetu_project_hetu_v1_crypto_bls12381.PublicKey
			m.BlsAggrPk = &v
			if err := m.BlsAggrPk.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PowerSum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PowerSum = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lifecycle", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lifecycle = append(m.Lifecycle, &CheckpointStateUpdateResponse{})
			if err := m.Lifecycle[len(m.Lifecycle)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
