// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: hetu/blockinflation/v1/genesis.proto

package types

import (
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenesisState defines the blockinflation module's genesis state.
type GenesisState struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Params               *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	TotalIssuance        *types.Coin            `protobuf:"bytes,2,opt,name=total_issuance,json=totalIssuance,proto3" json:"total_issuance,omitempty"`
	TotalBurned          *types.Coin            `protobuf:"bytes,3,opt,name=total_burned,json=totalBurned,proto3" json:"total_burned,omitempty"`
	PendingSubnetRewards *types.Coin            `protobuf:"bytes,4,opt,name=pending_subnet_rewards,json=pendingSubnetRewards,proto3" json:"pending_subnet_rewards,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_hetu_blockinflation_v1_genesis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_hetu_blockinflation_v1_genesis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_hetu_blockinflation_v1_genesis_proto_rawDescGZIP(), []int{0}
}

func (x *GenesisState) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GenesisState) GetTotalIssuance() *types.Coin {
	if x != nil {
		return x.TotalIssuance
	}
	return nil
}

func (x *GenesisState) GetTotalBurned() *types.Coin {
	if x != nil {
		return x.TotalBurned
	}
	return nil
}

func (x *GenesisState) GetPendingSubnetRewards() *types.Coin {
	if x != nil {
		return x.PendingSubnetRewards
	}
	return nil
}

var File_hetu_blockinflation_v1_genesis_proto protoreflect.FileDescriptor

const file_hetu_blockinflation_v1_genesis_proto_rawDesc = "" +
	"\n" +
	"$hetu/blockinflation/v1/genesis.proto\x12\x16hetu.blockinflation.v1\x1a\x14gogoproto/gogo.proto\x1a\x1ecosmos/base/v1beta1/coin.proto\x1a\"hetu/blockinflation/v1/query.proto\"\xaf\x02\n" +
	"\fGenesisState\x12<\n" +
	"\x06params\x18\x01 \x01(\v2\x1e.hetu.blockinflation.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params\x12F\n" +
	"\x0etotal_issuance\x18\x02 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\rtotalIssuance\x12B\n" +
	"\ftotal_burned\x18\x03 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\vtotalBurned\x12U\n" +
	"\x16pending_subnet_rewards\x18\x04 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x14pendingSubnetRewardsB8Z6github.com/hetu-project/hetu/v1/x/blockinflation/typesb\x06proto3"

var (
	file_hetu_blockinflation_v1_genesis_proto_rawDescOnce sync.Once
	file_hetu_blockinflation_v1_genesis_proto_rawDescData []byte
)

func file_hetu_blockinflation_v1_genesis_proto_rawDescGZIP() []byte {
	file_hetu_blockinflation_v1_genesis_proto_rawDescOnce.Do(func() {
		file_hetu_blockinflation_v1_genesis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hetu_blockinflation_v1_genesis_proto_rawDesc), len(file_hetu_blockinflation_v1_genesis_proto_rawDesc)))
	})
	return file_hetu_blockinflation_v1_genesis_proto_rawDescData
}

var file_hetu_blockinflation_v1_genesis_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hetu_blockinflation_v1_genesis_proto_goTypes = []any{
	(*GenesisState)(nil), // 0: hetu.blockinflation.v1.GenesisState
	(*Params)(nil),       // 1: hetu.blockinflation.v1.Params
	(*types.Coin)(nil),   // 2: cosmos.base.v1beta1.Coin
}
var file_hetu_blockinflation_v1_genesis_proto_depIdxs = []int32{
	1, // 0: hetu.blockinflation.v1.GenesisState.params:type_name -> hetu.blockinflation.v1.Params
	2, // 1: hetu.blockinflation.v1.GenesisState.total_issuance:type_name -> cosmos.base.v1beta1.Coin
	2, // 2: hetu.blockinflation.v1.GenesisState.total_burned:type_name -> cosmos.base.v1beta1.Coin
	2, // 3: hetu.blockinflation.v1.GenesisState.pending_subnet_rewards:type_name -> cosmos.base.v1beta1.Coin
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_hetu_blockinflation_v1_genesis_proto_init() }
func file_hetu_blockinflation_v1_genesis_proto_init() {
	if File_hetu_blockinflation_v1_genesis_proto != nil {
		return
	}
	file_hetu_blockinflation_v1_query_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hetu_blockinflation_v1_genesis_proto_rawDesc), len(file_hetu_blockinflation_v1_genesis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hetu_blockinflation_v1_genesis_proto_goTypes,
		DependencyIndexes: file_hetu_blockinflation_v1_genesis_proto_depIdxs,
		MessageInfos:      file_hetu_blockinflation_v1_genesis_proto_msgTypes,
	}.Build()
	File_hetu_blockinflation_v1_genesis_proto = out.File
	file_hetu_blockinflation_v1_genesis_proto_goTypes = nil
	file_hetu_blockinflation_v1_genesis_proto_depIdxs = nil
}
