// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: hetu/blockinflation/v1/query.proto

package types

import (
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_hetu_blockinflation_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hetu_blockinflation_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_hetu_blockinflation_v1_query_proto_rawDescGZIP(), []int{0}
}

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// params defines the parameters of the module.
	Params        *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_hetu_blockinflation_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hetu_blockinflation_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_hetu_blockinflation_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

// QueryPendingSubnetRewardsRequest is the request type for the Query/PendingSubnetRewards RPC method.
type QueryPendingSubnetRewardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPendingSubnetRewardsRequest) Reset() {
	*x = QueryPendingSubnetRewardsRequest{}
	mi := &file_hetu_blockinflation_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPendingSubnetRewardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPendingSubnetRewardsRequest) ProtoMessage() {}

func (x *QueryPendingSubnetRewardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hetu_blockinflation_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPendingSubnetRewardsRequest.ProtoReflect.Descriptor instead.
func (*QueryPendingSubnetRewardsRequest) Descriptor() ([]byte, []int) {
	return file_hetu_blockinflation_v1_query_proto_rawDescGZIP(), []int{2}
}

// QueryPendingSubnetRewardsResponse is the response type for the Query/PendingSubnetRewards RPC method.
type QueryPendingSubnetRewardsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pending_subnet_rewards defines the pending subnet rewards.
	PendingSubnetRewards *types.Coin `protobuf:"bytes,1,opt,name=pending_subnet_rewards,json=pendingSubnetRewards,proto3" json:"pending_subnet_rewards,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *QueryPendingSubnetRewardsResponse) Reset() {
	*x = QueryPendingSubnetRewardsResponse{}
	mi := &file_hetu_blockinflation_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPendingSubnetRewardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPendingSubnetRewardsResponse) ProtoMessage() {}

func (x *QueryPendingSubnetRewardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hetu_blockinflation_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPendingSubnetRewardsResponse.ProtoReflect.Descriptor instead.
func (*QueryPendingSubnetRewardsResponse) Descriptor() ([]byte, []int) {
	return file_hetu_blockinflation_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryPendingSubnetRewardsResponse) GetPendingSubnetRewards() *types.Coin {
	if x != nil {
		return x.PendingSubnetRewards
	}
	return nil
}

// Params defines the parameters for the blockinflation module.
type Params struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	EnableBlockInflation bool                   `protobuf:"varint,1,opt,name=enable_block_inflation,json=enableBlockInflation,proto3" json:"enable_block_inflation,omitempty"`
	MintDenom            string                 `protobuf:"bytes,2,opt,name=mint_denom,json=mintDenom,proto3" json:"mint_denom,omitempty"`
	TotalSupply          string                 `protobuf:"bytes,3,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	DefaultBlockEmission string                 `protobuf:"bytes,4,opt,name=default_block_emission,json=defaultBlockEmission,proto3" json:"default_block_emission,omitempty"`
	SubnetRewardBase     string                 `protobuf:"bytes,5,opt,name=subnet_reward_base,json=subnetRewardBase,proto3" json:"subnet_reward_base,omitempty"`
	SubnetRewardK        string                 `protobuf:"bytes,6,opt,name=subnet_reward_k,json=subnetRewardK,proto3" json:"subnet_reward_k,omitempty"`
	SubnetRewardMaxRatio string                 `protobuf:"bytes,7,opt,name=subnet_reward_max_ratio,json=subnetRewardMaxRatio,proto3" json:"subnet_reward_max_ratio,omitempty"`
	SubnetMovingAlpha    string                 `protobuf:"bytes,8,opt,name=subnet_moving_alpha,json=subnetMovingAlpha,proto3" json:"subnet_moving_alpha,omitempty"`
	SubnetOwnerCut       string                 `protobuf:"bytes,9,opt,name=subnet_owner_cut,json=subnetOwnerCut,proto3" json:"subnet_owner_cut,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_hetu_blockinflation_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_hetu_blockinflation_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_hetu_blockinflation_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *Params) GetEnableBlockInflation() bool {
	if x != nil {
		return x.EnableBlockInflation
	}
	return false
}

func (x *Params) GetMintDenom() string {
	if x != nil {
		return x.MintDenom
	}
	return ""
}

func (x *Params) GetTotalSupply() string {
	if x != nil {
		return x.TotalSupply
	}
	return ""
}

func (x *Params) GetDefaultBlockEmission() string {
	if x != nil {
		return x.DefaultBlockEmission
	}
	return ""
}

func (x *Params) GetSubnetRewardBase() string {
	if x != nil {
		return x.SubnetRewardBase
	}
	return ""
}

func (x *Params) GetSubnetRewardK() string {
	if x != nil {
		return x.SubnetRewardK
	}
	return ""
}

func (x *Params) GetSubnetRewardMaxRatio() string {
	if x != nil {
		return x.SubnetRewardMaxRatio
	}
	return ""
}

func (x *Params) GetSubnetMovingAlpha() string {
	if x != nil {
		return x.SubnetMovingAlpha
	}
	return ""
}

func (x *Params) GetSubnetOwnerCut() string {
	if x != nil {
		return x.SubnetOwnerCut
	}
	return ""
}

var File_hetu_blockinflation_v1_query_proto protoreflect.FileDescriptor

const file_hetu_blockinflation_v1_query_proto_rawDesc = "" +
	"\n" +
	"\"hetu/blockinflation/v1/query.proto\x12\x16hetu.blockinflation.v1\x1a\x14gogoproto/gogo.proto\x1a\x1ecosmos/base/v1beta1/coin.proto\x1a\x1cgoogle/api/annotations.proto\"\x14\n" +
	"\x12QueryParamsRequest\"S\n" +
	"\x13QueryParamsResponse\x12<\n" +
	"\x06params\x18\x01 \x01(\v2\x1e.hetu.blockinflation.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params\"\"\n" +
	" QueryPendingSubnetRewardsRequest\"z\n" +
	"!QueryPendingSubnetRewardsResponse\x12U\n" +
	"\x16pending_subnet_rewards\x18\x01 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x14pendingSubnetRewards\"\x9a\x05\n" +
	"\x06Params\x124\n" +
	"\x16enable_block_inflation\x18\x01 \x01(\bR\x14enableBlockInflation\x12\x1d\n" +
	"\n" +
	"mint_denom\x18\x02 \x01(\tR\tmintDenom\x12@\n" +
	"\ftotal_supply\x18\x03 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\vtotalSupply\x12S\n" +
	"\x16default_block_emission\x18\x04 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\x14defaultBlockEmission\x12Q\n" +
	"\x12subnet_reward_base\x18\x05 \x01(\tB#\xc8\xde\x1f\x00\xda\xde\x1f\x1bcosmossdk.io/math.LegacyDecR\x10subnetRewardBase\x12K\n" +
	"\x0fsubnet_reward_k\x18\x06 \x01(\tB#\xc8\xde\x1f\x00\xda\xde\x1f\x1bcosmossdk.io/math.LegacyDecR\rsubnetRewardK\x12Z\n" +
	"\x17subnet_reward_max_ratio\x18\a \x01(\tB#\xc8\xde\x1f\x00\xda\xde\x1f\x1bcosmossdk.io/math.LegacyDecR\x14subnetRewardMaxRatio\x12S\n" +
	"\x13subnet_moving_alpha\x18\b \x01(\tB#\xc8\xde\x1f\x00\xda\xde\x1f\x1bcosmossdk.io/math.LegacyDecR\x11subnetMovingAlpha\x12M\n" +
	"\x10subnet_owner_cut\x18\t \x01(\tB#\xc8\xde\x1f\x00\xda\xde\x1f\x1bcosmossdk.io/math.LegacyDecR\x0esubnetOwnerCut:\x04\x98\xa0\x1f\x002\xd9\x02\n" +
	"\x05Query\x12\x89\x01\n" +
	"\x06Params\x12*.hetu.blockinflation.v1.QueryParamsRequest\x1a+.hetu.blockinflation.v1.QueryParamsResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/hetu/blockinflation/v1/params\x12\xc3\x01\n" +
	"\x14PendingSubnetRewards\x128.hetu.blockinflation.v1.QueryPendingSubnetRewardsRequest\x1a9.hetu.blockinflation.v1.QueryPendingSubnetRewardsResponse\"6\x82\xd3\xe4\x93\x020\x12./hetu/blockinflation/v1/pending_subnet_rewardsB8Z6github.com/hetu-project/hetu/v1/x/blockinflation/typesb\x06proto3"

var (
	file_hetu_blockinflation_v1_query_proto_rawDescOnce sync.Once
	file_hetu_blockinflation_v1_query_proto_rawDescData []byte
)

func file_hetu_blockinflation_v1_query_proto_rawDescGZIP() []byte {
	file_hetu_blockinflation_v1_query_proto_rawDescOnce.Do(func() {
		file_hetu_blockinflation_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hetu_blockinflation_v1_query_proto_rawDesc), len(file_hetu_blockinflation_v1_query_proto_rawDesc)))
	})
	return file_hetu_blockinflation_v1_query_proto_rawDescData
}

var file_hetu_blockinflation_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_hetu_blockinflation_v1_query_proto_goTypes = []any{
	(*QueryParamsRequest)(nil),                // 0: hetu.blockinflation.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil),               // 1: hetu.blockinflation.v1.QueryParamsResponse
	(*QueryPendingSubnetRewardsRequest)(nil),  // 2: hetu.blockinflation.v1.QueryPendingSubnetRewardsRequest
	(*QueryPendingSubnetRewardsResponse)(nil), // 3: hetu.blockinflation.v1.QueryPendingSubnetRewardsResponse
	(*Params)(nil),                            // 4: hetu.blockinflation.v1.Params
	(*types.Coin)(nil),                        // 5: cosmos.base.v1beta1.Coin
}
var file_hetu_blockinflation_v1_query_proto_depIdxs = []int32{
	4, // 0: hetu.blockinflation.v1.QueryParamsResponse.params:type_name -> hetu.blockinflation.v1.Params
	5, // 1: hetu.blockinflation.v1.QueryPendingSubnetRewardsResponse.pending_subnet_rewards:type_name -> cosmos.base.v1beta1.Coin
	0, // 2: hetu.blockinflation.v1.Query.Params:input_type -> hetu.blockinflation.v1.QueryParamsRequest
	2, // 3: hetu.blockinflation.v1.Query.PendingSubnetRewards:input_type -> hetu.blockinflation.v1.QueryPendingSubnetRewardsRequest
	1, // 4: hetu.blockinflation.v1.Query.Params:output_type -> hetu.blockinflation.v1.QueryParamsResponse
	3, // 5: hetu.blockinflation.v1.Query.PendingSubnetRewards:output_type -> hetu.blockinflation.v1.QueryPendingSubnetRewardsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hetu_blockinflation_v1_query_proto_init() }
func file_hetu_blockinflation_v1_query_proto_init() {
	if File_hetu_blockinflation_v1_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hetu_blockinflation_v1_query_proto_rawDesc), len(file_hetu_blockinflation_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hetu_blockinflation_v1_query_proto_goTypes,
		DependencyIndexes: file_hetu_blockinflation_v1_query_proto_depIdxs,
		MessageInfos:      file_hetu_blockinflation_v1_query_proto_msgTypes,
	}.Build()
	File_hetu_blockinflation_v1_query_proto = out.File
	file_hetu_blockinflation_v1_query_proto_goTypes = nil
	file_hetu_blockinflation_v1_query_proto_depIdxs = nil
}
