// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: hetu/checkpointing/v1/tx.proto

package checkpointingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_RegistValidator_FullMethodName     = "/hetu.checkpointing.v1.Msg/RegistValidator"
	Msg_RegistStakeContract_FullMethodName = "/hetu.checkpointing.v1.Msg/RegistStakeContract"
	Msg_BLSCallback_FullMethodName         = "/hetu.checkpointing.v1.Msg/BLSCallback"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// RegistValidator defines a method for registering a new validator of the checkpoint network
	RegistValidator(ctx context.Context, in *MsgRegistValidator, opts ...grpc.CallOption) (*MsgRegistValidatorResponse, error)
	// RegistStakeContract defines a method for registering a validator's staking contract address
	RegistStakeContract(ctx context.Context, in *MsgRegistStakeContract, opts ...grpc.CallOption) (*MsgRegistStakeContractResponse, error)
	// BLSCallback defines a method for uploading BLS signature
	BLSCallback(ctx context.Context, in *MsgBLSCallback, opts ...grpc.CallOption) (*MsgBLSCallbackResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegistValidator(ctx context.Context, in *MsgRegistValidator, opts ...grpc.CallOption) (*MsgRegistValidatorResponse, error) {
	out := new(MsgRegistValidatorResponse)
	err := c.cc.Invoke(ctx, Msg_RegistValidator_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegistStakeContract(ctx context.Context, in *MsgRegistStakeContract, opts ...grpc.CallOption) (*MsgRegistStakeContractResponse, error) {
	out := new(MsgRegistStakeContractResponse)
	err := c.cc.Invoke(ctx, Msg_RegistStakeContract_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BLSCallback(ctx context.Context, in *MsgBLSCallback, opts ...grpc.CallOption) (*MsgBLSCallbackResponse, error) {
	out := new(MsgBLSCallbackResponse)
	err := c.cc.Invoke(ctx, Msg_BLSCallback_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// RegistValidator defines a method for registering a new validator of the checkpoint network
	RegistValidator(context.Context, *MsgRegistValidator) (*MsgRegistValidatorResponse, error)
	// RegistStakeContract defines a method for registering a validator's staking contract address
	RegistStakeContract(context.Context, *MsgRegistStakeContract) (*MsgRegistStakeContractResponse, error)
	// BLSCallback defines a method for uploading BLS signature
	BLSCallback(context.Context, *MsgBLSCallback) (*MsgBLSCallbackResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) RegistValidator(context.Context, *MsgRegistValidator) (*MsgRegistValidatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegistValidator not implemented")
}
func (UnimplementedMsgServer) RegistStakeContract(context.Context, *MsgRegistStakeContract) (*MsgRegistStakeContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegistStakeContract not implemented")
}
func (UnimplementedMsgServer) BLSCallback(context.Context, *MsgBLSCallback) (*MsgBLSCallbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BLSCallback not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_RegistValidator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegistValidator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegistValidator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RegistValidator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegistValidator(ctx, req.(*MsgRegistValidator))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegistStakeContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegistStakeContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegistStakeContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RegistStakeContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegistStakeContract(ctx, req.(*MsgRegistStakeContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BLSCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBLSCallback)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BLSCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_BLSCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BLSCallback(ctx, req.(*MsgBLSCallback))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hetu.checkpointing.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegistValidator",
			Handler:    _Msg_RegistValidator_Handler,
		},
		{
			MethodName: "RegistStakeContract",
			Handler:    _Msg_RegistStakeContract_Handler,
		},
		{
			MethodName: "BLSCallback",
			Handler:    _Msg_BLSCallback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hetu/checkpointing/v1/tx.proto",
}
