// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: ethermint/feemarket/v1/events.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventFeeMarket is the event type for the fee market module
type EventFeeMarket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// base_fee for EIP-1559 blocks
	BaseFee string `protobuf:"bytes,1,opt,name=base_fee,json=baseFee,proto3" json:"base_fee,omitempty"`
}

func (x *EventFeeMarket) Reset() {
	*x = EventFeeMarket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ethermint_feemarket_v1_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventFeeMarket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFeeMarket) ProtoMessage() {}

func (x *EventFeeMarket) ProtoReflect() protoreflect.Message {
	mi := &file_ethermint_feemarket_v1_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFeeMarket.ProtoReflect.Descriptor instead.
func (*EventFeeMarket) Descriptor() ([]byte, []int) {
	return file_ethermint_feemarket_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventFeeMarket) GetBaseFee() string {
	if x != nil {
		return x.BaseFee
	}
	return ""
}

// EventBlockGas defines an Ethereum block gas event
type EventBlockGas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// height of the block
	Height string `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
	// amount of gas wanted by the block
	Amount string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *EventBlockGas) Reset() {
	*x = EventBlockGas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ethermint_feemarket_v1_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventBlockGas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBlockGas) ProtoMessage() {}

func (x *EventBlockGas) ProtoReflect() protoreflect.Message {
	mi := &file_ethermint_feemarket_v1_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBlockGas.ProtoReflect.Descriptor instead.
func (*EventBlockGas) Descriptor() ([]byte, []int) {
	return file_ethermint_feemarket_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *EventBlockGas) GetHeight() string {
	if x != nil {
		return x.Height
	}
	return ""
}

func (x *EventBlockGas) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

var File_ethermint_feemarket_v1_events_proto protoreflect.FileDescriptor

var file_ethermint_feemarket_v1_events_proto_rawDesc = []byte{
	0x0a, 0x23, 0x65, 0x74, 0x68, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x74, 0x2f, 0x66, 0x65, 0x65, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x65, 0x74, 0x68, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x74,
	0x2e, 0x66, 0x65, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x22, 0x2b, 0x0a,
	0x0e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x65, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x62, 0x61, 0x73, 0x65, 0x46, 0x65, 0x65, 0x22, 0x3f, 0x0a, 0x0d, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x47, 0x61, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x33, 0x5a, 0x31, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x65, 0x74, 0x75, 0x2d, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x68, 0x65, 0x74, 0x75, 0x2f, 0x76, 0x31, 0x2f, 0x78,
	0x2f, 0x66, 0x65, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ethermint_feemarket_v1_events_proto_rawDescOnce sync.Once
	file_ethermint_feemarket_v1_events_proto_rawDescData = file_ethermint_feemarket_v1_events_proto_rawDesc
)

func file_ethermint_feemarket_v1_events_proto_rawDescGZIP() []byte {
	file_ethermint_feemarket_v1_events_proto_rawDescOnce.Do(func() {
		file_ethermint_feemarket_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_ethermint_feemarket_v1_events_proto_rawDescData)
	})
	return file_ethermint_feemarket_v1_events_proto_rawDescData
}

var file_ethermint_feemarket_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ethermint_feemarket_v1_events_proto_goTypes = []interface{}{
	(*EventFeeMarket)(nil), // 0: ethermint.feemarket.v1.EventFeeMarket
	(*EventBlockGas)(nil),  // 1: ethermint.feemarket.v1.EventBlockGas
}
var file_ethermint_feemarket_v1_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ethermint_feemarket_v1_events_proto_init() }
func file_ethermint_feemarket_v1_events_proto_init() {
	if File_ethermint_feemarket_v1_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ethermint_feemarket_v1_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventFeeMarket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ethermint_feemarket_v1_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventBlockGas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ethermint_feemarket_v1_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ethermint_feemarket_v1_events_proto_goTypes,
		DependencyIndexes: file_ethermint_feemarket_v1_events_proto_depIdxs,
		MessageInfos:      file_ethermint_feemarket_v1_events_proto_msgTypes,
	}.Build()
	File_ethermint_feemarket_v1_events_proto = out.File
	file_ethermint_feemarket_v1_events_proto_rawDesc = nil
	file_ethermint_feemarket_v1_events_proto_goTypes = nil
	file_ethermint_feemarket_v1_events_proto_depIdxs = nil
}
